// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     User approved the command, and wants to apply the proposed execpolicy amendment so future matching commands can run without prompting.
/// </summary>
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public class AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision : CommandExecutionApprovalDecision
{
    [JsonPropertyName("acceptWithExecpolicyAmendment")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment AcceptWithExecpolicyAmendment { get; set; } = default!;

}
