// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Sparse rolling rate-limit update.
///     
///     Clients should merge available values into the most recent `account/rateLimits/read` response or refetch that snapshot. Nullable account metadata may be unavailable in a rolling update and does not clear a previously observed value.
/// </summary>
public class AccountRateLimitsUpdatedNotification
{
    [JsonPropertyName("rateLimits")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RateLimitSnapshot RateLimits { get; set; } = default!;

}
