// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ActiveThreadStatus : ThreadStatus
{
    [JsonPropertyName("activeFlags")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ThreadActiveFlag> ActiveFlags { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "active";
        private set
        {
            if (value != "active")
            {
                throw new JsonException("Expected ActiveThreadStatus.type to be active.");
            }
        }
    }

}
