// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Returned when `turn/start` or `turn/steer` is submitted while the current active turn cannot accept same-turn steering, for example `/review` or manual `/compact`.
/// </summary>
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public class ActiveTurnNotSteerableCodexErrorInfo : CodexErrorInfo
{
    [JsonPropertyName("activeTurnNotSteerable")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CodexErrorInfoActiveTurnNotSteerable ActiveTurnNotSteerable { get; set; } = default!;

}
