// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(AddCreditsNudgeCreditTypeJsonConverter))]
public enum AddCreditsNudgeCreditType
{
    Credits,
    UsageLimit,
}
