// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class AdditionalPermissionProfile
{
    [JsonPropertyName("fileSystem")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AdditionalFileSystemPermissions?> FileSystem { get; set; }

    /// <summary>
    ///     Partial overlay used for per-command permission requests.
    /// </summary>
    [JsonPropertyName("network")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AdditionalNetworkPermissions?> Network { get; set; }

}
