// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class AgentMessageResponseItem : ResponseItem
{
    [JsonPropertyName("author")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Author { get; set; } = default!;

    [JsonPropertyName("content")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<AgentMessageInputContent> Content { get; set; } = default!;

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Id { get; set; }

    [JsonPropertyName("internal_chat_message_metadata_passthrough")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternalChatMessageMetadataPassthrough?> InternalChatMessageMetadataPassthrough { get; set; }

    [JsonPropertyName("recipient")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Recipient { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "agent_message";
        private set
        {
            if (value != "agent_message")
            {
                throw new JsonException("Expected AgentMessageResponseItem.type to be agent_message.");
            }
        }
    }

}
