// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class AllowDenyRequirementJsonConverter : JsonConverter<AllowDenyRequirement>
{
    private static AllowDenyRequirement Parse(string? value) => value switch
    {
        "allow" => AllowDenyRequirement.Allow,
        "deny" => AllowDenyRequirement.Deny,
        _ => throw new JsonException("Unknown AllowDenyRequirement value: " + value)
    };
    private static string Format(AllowDenyRequirement value) => value switch
    {
        AllowDenyRequirement.Allow => "allow",
        AllowDenyRequirement.Deny => "deny",
        _ => throw new JsonException("Unknown AllowDenyRequirement value: " + value)
    };
    public override AllowDenyRequirement Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for AllowDenyRequirement.");
    public override void Write(Utf8JsonWriter writer, AllowDenyRequirement value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override AllowDenyRequirement ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, AllowDenyRequirement value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
