// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL - notification emitted when the app list changes.
/// </summary>
public class AppListUpdatedNotification
{
    [JsonPropertyName("data")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<AppInfo> Data { get; set; } = default!;

}
