// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ApplyPatchApprovalResponse
{
    [JsonPropertyName("decision")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ReviewDecision Decision { get; set; } = default!;

}
