// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL - app/read response.
/// </summary>
public class AppsReadResponse
{
    [JsonPropertyName("apps")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ConnectorMetadata> Apps { get; set; } = default!;

    [JsonPropertyName("missingAppIds")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> MissingAppIds { get; set; } = default!;

}
