// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class AppsDefaultConfig
{
    [JsonPropertyName("approvals_reviewer")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ApprovalsReviewer?> ApprovalsReviewer { get; set; }

    [JsonPropertyName("default_tools_approval_mode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AppToolApproval?> DefaultToolsApprovalMode { get; set; }

    [JsonPropertyName("destructive_enabled")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> DestructiveEnabled { get; set; }

    [JsonPropertyName("enabled")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> Enabled { get; set; }

    [JsonPropertyName("open_world_enabled")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> OpenWorldEnabled { get; set; }

}
