// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class AppTemplateUnavailableReasonJsonConverter : JsonConverter<AppTemplateUnavailableReason>
{
    private static AppTemplateUnavailableReason Parse(string? value) => value switch
    {
        "NOT_CONFIGURED_FOR_WORKSPACE" => AppTemplateUnavailableReason.NOTCONFIGUREDFORWORKSPACE,
        "NO_ACTIVE_WORKSPACE" => AppTemplateUnavailableReason.NOACTIVEWORKSPACE,
        _ => throw new JsonException("Unknown AppTemplateUnavailableReason value: " + value)
    };
    private static string Format(AppTemplateUnavailableReason value) => value switch
    {
        AppTemplateUnavailableReason.NOTCONFIGUREDFORWORKSPACE => "NOT_CONFIGURED_FOR_WORKSPACE",
        AppTemplateUnavailableReason.NOACTIVEWORKSPACE => "NO_ACTIVE_WORKSPACE",
        _ => throw new JsonException("Unknown AppTemplateUnavailableReason value: " + value)
    };
    public override AppTemplateUnavailableReason Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for AppTemplateUnavailableReason.");
    public override void Write(Utf8JsonWriter writer, AppTemplateUnavailableReason value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override AppTemplateUnavailableReason ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, AppTemplateUnavailableReason value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
