// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class AskForApprovalJsonConverter : JsonConverter<AskForApproval>
{
    public override AskForApproval Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind == JsonValueKind.Object && root.TryGetProperty("granular", out var property0))
            return root.Deserialize<GranularAskForApproval>(options) ?? throw new JsonException("Expected GranularAskForApproval.");
        if (root.ValueKind == JsonValueKind.String && root.GetString() == "never")
            return new AskForApprovalNever();
        if (root.ValueKind == JsonValueKind.String && root.GetString() == "on-request")
            return new AskForApprovalOnRequest();
        if (root.ValueKind == JsonValueKind.String && root.GetString() == "untrusted")
            return new AskForApprovalUntrusted();
        throw new JsonException("Unknown AskForApproval wire shape or value.");
    }

    public override void Write(Utf8JsonWriter writer, AskForApproval value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case GranularAskForApproval concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AskForApprovalNever concrete:
                writer.WriteStringValue("never");
                break;
            case AskForApprovalOnRequest concrete:
                writer.WriteStringValue("on-request");
                break;
            case AskForApprovalUntrusted concrete:
                writer.WriteStringValue("untrusted");
                break;
            default: throw new JsonException("Unknown runtime type for AskForApproval.");
        }
    }
}
