// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Authentication mode for OpenAI-backed providers.
/// </summary>
[JsonConverter(typeof(AuthModeJsonConverter))]
public enum AuthMode
{
    AgentIdentity,
    Apikey,
    BedrockAccessKeys,
    BedrockApiKey,
    Chatgpt,
    ChatgptAuthTokens,
    Headers,
    PersonalAccessToken,
}
