// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class AuthModeJsonConverter : JsonConverter<AuthMode>
{
    private static AuthMode Parse(string? value) => value switch
    {
        "agentIdentity" => AuthMode.AgentIdentity,
        "apikey" => AuthMode.Apikey,
        "bedrockAccessKeys" => AuthMode.BedrockAccessKeys,
        "bedrockApiKey" => AuthMode.BedrockApiKey,
        "chatgpt" => AuthMode.Chatgpt,
        "chatgptAuthTokens" => AuthMode.ChatgptAuthTokens,
        "headers" => AuthMode.Headers,
        "personalAccessToken" => AuthMode.PersonalAccessToken,
        _ => throw new JsonException("Unknown AuthMode value: " + value)
    };
    private static string Format(AuthMode value) => value switch
    {
        AuthMode.AgentIdentity => "agentIdentity",
        AuthMode.Apikey => "apikey",
        AuthMode.BedrockAccessKeys => "bedrockAccessKeys",
        AuthMode.BedrockApiKey => "bedrockApiKey",
        AuthMode.Chatgpt => "chatgpt",
        AuthMode.ChatgptAuthTokens => "chatgptAuthTokens",
        AuthMode.Headers => "headers",
        AuthMode.PersonalAccessToken => "personalAccessToken",
        _ => throw new JsonException("Unknown AuthMode value: " + value)
    };
    public override AuthMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for AuthMode.");
    public override void Write(Utf8JsonWriter writer, AuthMode value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override AuthMode ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, AuthMode value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
