// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class BemItemPromotedThreadRealtimeItem : ThreadRealtimeItem
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    [JsonPropertyName("item_id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ItemId { get; set; } = default!;

    [JsonPropertyName("presentation")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadRealtimeBemItemPresentation Presentation { get; set; } = default!;

    [JsonPropertyName("realtimeSessionId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string RealtimeSessionId { get; set; } = default!;

    [JsonPropertyName("turn_id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string TurnId { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "bemItemPromoted";
        private set
        {
            if (value != "bemItemPromoted")
            {
                throw new JsonException("Expected BemItemPromotedThreadRealtimeItem.type to be bemItemPromoted.");
            }
        }
    }

}
