// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class BrowserUseAccessApprovalLifetimeJsonConverter : JsonConverter<BrowserUseAccessApprovalLifetime>
{
    private static BrowserUseAccessApprovalLifetime Parse(string? value) => value switch
    {
        "thread" => BrowserUseAccessApprovalLifetime.Thread,
        "turn" => BrowserUseAccessApprovalLifetime.Turn,
        _ => throw new JsonException("Unknown BrowserUseAccessApprovalLifetime value: " + value)
    };
    private static string Format(BrowserUseAccessApprovalLifetime value) => value switch
    {
        BrowserUseAccessApprovalLifetime.Thread => "thread",
        BrowserUseAccessApprovalLifetime.Turn => "turn",
        _ => throw new JsonException("Unknown BrowserUseAccessApprovalLifetime value: " + value)
    };
    public override BrowserUseAccessApprovalLifetime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for BrowserUseAccessApprovalLifetime.");
    public override void Write(Utf8JsonWriter writer, BrowserUseAccessApprovalLifetime value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override BrowserUseAccessApprovalLifetime ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, BrowserUseAccessApprovalLifetime value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
