// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class BrowserUseConfig
{
    [JsonPropertyName("allow_history_access")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> AllowHistoryAccess { get; set; }

    [JsonPropertyName("default_origin_policy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<BrowserUseOriginPolicyConfig?> DefaultOriginPolicy { get; set; }

    [JsonPropertyName("origins")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Dictionary<string, BrowserUseOriginPolicyConfig>?> Origins { get; set; }

}
