// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class BrowserUseRequirements
{
    [JsonPropertyName("allowGlobalPersistentApproval")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> AllowGlobalPersistentApproval { get; set; }

    [JsonPropertyName("allowHistoryAccess")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> AllowHistoryAccess { get; set; }

    [JsonPropertyName("defaultOriginPolicy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<BrowserUseOriginPolicy?> DefaultOriginPolicy { get; set; }

    [JsonPropertyName("disableAutoReview")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> DisableAutoReview { get; set; }

    [JsonPropertyName("origins")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Dictionary<string, BrowserUseOriginPolicy>?> Origins { get; set; }

}
