// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Location used to resolve a selected capability root.
/// </summary>
[JsonConverter(typeof(CapabilityRootLocationJsonConverter))]
public abstract class CapabilityRootLocation
{
    private protected CapabilityRootLocation() { }
}
