// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CapabilityRootLocationJsonConverter : JsonConverter<CapabilityRootLocation>
{
    public override CapabilityRootLocation Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid CapabilityRootLocation type.");
        return discriminator.GetString() switch
        {
            "environment" => root.Deserialize<EnvironmentCapabilityRootLocation>(options) ?? throw new JsonException("Expected EnvironmentCapabilityRootLocation."),
            _ => throw new JsonException("Unknown CapabilityRootLocation type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, CapabilityRootLocation value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case EnvironmentCapabilityRootLocation concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for CapabilityRootLocation.");
        }
    }
}
