// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class Chatgptv2LoginAccountParams : LoginAccountParams
{
    [JsonPropertyName("appBrand")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<LoginAppBrand?> AppBrand { get; set; }

    [JsonPropertyName("codexStreamlinedLogin")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> CodexStreamlinedLogin { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "chatgpt";
        private set
        {
            if (value != "chatgpt")
            {
                throw new JsonException("Expected Chatgptv2LoginAccountParams.type to be chatgpt.");
            }
        }
    }

    [JsonPropertyName("useHostedLoginSuccessPage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> UseHostedLoginSuccessPage { get; set; }

}
