// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CliAuthCredentialsStoreModeJsonConverter))]
public enum CliAuthCredentialsStoreMode
{
    Auto,
    Ephemeral,
    File,
    Keyring,
}
