// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CliAuthCredentialsStoreModeJsonConverter : JsonConverter<CliAuthCredentialsStoreMode>
{
    private static CliAuthCredentialsStoreMode Parse(string? value) => value switch
    {
        "auto" => CliAuthCredentialsStoreMode.Auto,
        "ephemeral" => CliAuthCredentialsStoreMode.Ephemeral,
        "file" => CliAuthCredentialsStoreMode.File,
        "keyring" => CliAuthCredentialsStoreMode.Keyring,
        _ => throw new JsonException("Unknown CliAuthCredentialsStoreMode value: " + value)
    };
    private static string Format(CliAuthCredentialsStoreMode value) => value switch
    {
        CliAuthCredentialsStoreMode.Auto => "auto",
        CliAuthCredentialsStoreMode.Ephemeral => "ephemeral",
        CliAuthCredentialsStoreMode.File => "file",
        CliAuthCredentialsStoreMode.Keyring => "keyring",
        _ => throw new JsonException("Unknown CliAuthCredentialsStoreMode value: " + value)
    };
    public override CliAuthCredentialsStoreMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for CliAuthCredentialsStoreMode.");
    public override void Write(Utf8JsonWriter writer, CliAuthCredentialsStoreMode value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override CliAuthCredentialsStoreMode ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, CliAuthCredentialsStoreMode value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
