// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Request from the client to the server.
/// </summary>
[JsonConverter(typeof(ClientRequestJsonConverter))]
public abstract class ClientRequest
{
    private protected ClientRequest() { }
}
