// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ClientNotificationJsonConverter : JsonConverter<ClientNotification>
{
    public override ClientNotification Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("method", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ClientNotification method.");
        return discriminator.GetString() switch
        {
            "initialized" => root.Deserialize<InitializedNotification>(options) ?? throw new JsonException("Expected InitializedNotification."),
            _ => throw new JsonException("Unknown ClientNotification method \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ClientNotification value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case InitializedNotification concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ClientNotification.");
        }
    }
}
