// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ClientRequestJsonConverter : JsonConverter<ClientRequest>
{
    public override ClientRequest Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("method", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ClientRequest method.");
        return discriminator.GetString() switch
        {
            "account/login/cancel" => root.Deserialize<AccountLoginCancelRequest>(options) ?? throw new JsonException("Expected AccountLoginCancelRequest."),
            "account/login/start" => root.Deserialize<AccountLoginStartRequest>(options) ?? throw new JsonException("Expected AccountLoginStartRequest."),
            "account/logout" => root.Deserialize<AccountLogoutRequest>(options) ?? throw new JsonException("Expected AccountLogoutRequest."),
            "account/rateLimitResetCredit/consume" => root.Deserialize<AccountRateLimitResetCreditConsumeRequest>(options) ?? throw new JsonException("Expected AccountRateLimitResetCreditConsumeRequest."),
            "account/rateLimits/read" => root.Deserialize<AccountRateLimitsReadRequest>(options) ?? throw new JsonException("Expected AccountRateLimitsReadRequest."),
            "account/read" => root.Deserialize<AccountReadRequest>(options) ?? throw new JsonException("Expected AccountReadRequest."),
            "account/sendAddCreditsNudgeEmail" => root.Deserialize<AccountSendAddCreditsNudgeEmailRequest>(options) ?? throw new JsonException("Expected AccountSendAddCreditsNudgeEmailRequest."),
            "account/usage/read" => root.Deserialize<AccountUsageReadRequest>(options) ?? throw new JsonException("Expected AccountUsageReadRequest."),
            "account/workspaceMessages/read" => root.Deserialize<AccountWorkspaceMessagesReadRequest>(options) ?? throw new JsonException("Expected AccountWorkspaceMessagesReadRequest."),
            "app/installed" => root.Deserialize<AppInstalledRequest>(options) ?? throw new JsonException("Expected AppInstalledRequest."),
            "app/list" => root.Deserialize<AppListRequest>(options) ?? throw new JsonException("Expected AppListRequest."),
            "app/read" => root.Deserialize<AppReadRequest>(options) ?? throw new JsonException("Expected AppReadRequest."),
            "command/exec" => root.Deserialize<CommandExecRequest>(options) ?? throw new JsonException("Expected CommandExecRequest."),
            "command/exec/resize" => root.Deserialize<CommandExecResizeRequest>(options) ?? throw new JsonException("Expected CommandExecResizeRequest."),
            "command/exec/terminate" => root.Deserialize<CommandExecTerminateRequest>(options) ?? throw new JsonException("Expected CommandExecTerminateRequest."),
            "command/exec/write" => root.Deserialize<CommandExecWriteRequest>(options) ?? throw new JsonException("Expected CommandExecWriteRequest."),
            "config/batchWrite" => root.Deserialize<ConfigBatchWriteRequest>(options) ?? throw new JsonException("Expected ConfigBatchWriteRequest."),
            "config/mcpServer/reload" => root.Deserialize<ConfigMcpServerReloadRequest>(options) ?? throw new JsonException("Expected ConfigMcpServerReloadRequest."),
            "config/read" => root.Deserialize<ConfigReadRequest>(options) ?? throw new JsonException("Expected ConfigReadRequest."),
            "config/value/write" => root.Deserialize<ConfigValueWriteRequest>(options) ?? throw new JsonException("Expected ConfigValueWriteRequest."),
            "configRequirements/read" => root.Deserialize<ConfigRequirementsReadRequest>(options) ?? throw new JsonException("Expected ConfigRequirementsReadRequest."),
            "experimentalFeature/enablement/set" => root.Deserialize<ExperimentalFeatureEnablementSetRequest>(options) ?? throw new JsonException("Expected ExperimentalFeatureEnablementSetRequest."),
            "experimentalFeature/list" => root.Deserialize<ExperimentalFeatureListRequest>(options) ?? throw new JsonException("Expected ExperimentalFeatureListRequest."),
            "externalAgentConfig/detect" => root.Deserialize<ExternalAgentConfigDetectRequest>(options) ?? throw new JsonException("Expected ExternalAgentConfigDetectRequest."),
            "externalAgentConfig/import" => root.Deserialize<ExternalAgentConfigImportRequest>(options) ?? throw new JsonException("Expected ExternalAgentConfigImportRequest."),
            "externalAgentConfig/import/readHistories" => root.Deserialize<ExternalAgentConfigImportReadHistoriesRequest>(options) ?? throw new JsonException("Expected ExternalAgentConfigImportReadHistoriesRequest."),
            "externalAgentConfig/import/recordHistory" => root.Deserialize<ExternalAgentConfigImportRecordHistoryRequest>(options) ?? throw new JsonException("Expected ExternalAgentConfigImportRecordHistoryRequest."),
            "feedback/upload" => root.Deserialize<FeedbackUploadRequest>(options) ?? throw new JsonException("Expected FeedbackUploadRequest."),
            "fs/copy" => root.Deserialize<FsCopyRequest>(options) ?? throw new JsonException("Expected FsCopyRequest."),
            "fs/createDirectory" => root.Deserialize<FsCreateDirectoryRequest>(options) ?? throw new JsonException("Expected FsCreateDirectoryRequest."),
            "fs/getMetadata" => root.Deserialize<FsGetMetadataRequest>(options) ?? throw new JsonException("Expected FsGetMetadataRequest."),
            "fs/readDirectory" => root.Deserialize<FsReadDirectoryRequest>(options) ?? throw new JsonException("Expected FsReadDirectoryRequest."),
            "fs/readFile" => root.Deserialize<FsReadFileRequest>(options) ?? throw new JsonException("Expected FsReadFileRequest."),
            "fs/remove" => root.Deserialize<FsRemoveRequest>(options) ?? throw new JsonException("Expected FsRemoveRequest."),
            "fs/unwatch" => root.Deserialize<FsUnwatchRequest>(options) ?? throw new JsonException("Expected FsUnwatchRequest."),
            "fs/watch" => root.Deserialize<FsWatchRequest>(options) ?? throw new JsonException("Expected FsWatchRequest."),
            "fs/writeFile" => root.Deserialize<FsWriteFileRequest>(options) ?? throw new JsonException("Expected FsWriteFileRequest."),
            "fuzzyFileSearch" => root.Deserialize<FuzzyFileSearchRequest>(options) ?? throw new JsonException("Expected FuzzyFileSearchRequest."),
            "hooks/list" => root.Deserialize<HooksListRequest>(options) ?? throw new JsonException("Expected HooksListRequest."),
            "initialize" => root.Deserialize<InitializeRequest>(options) ?? throw new JsonException("Expected InitializeRequest."),
            "marketplace/add" => root.Deserialize<MarketplaceAddRequest>(options) ?? throw new JsonException("Expected MarketplaceAddRequest."),
            "marketplace/remove" => root.Deserialize<MarketplaceRemoveRequest>(options) ?? throw new JsonException("Expected MarketplaceRemoveRequest."),
            "marketplace/upgrade" => root.Deserialize<MarketplaceUpgradeRequest>(options) ?? throw new JsonException("Expected MarketplaceUpgradeRequest."),
            "mcpServer/oauth/login" => root.Deserialize<McpServerOauthLoginRequest>(options) ?? throw new JsonException("Expected McpServerOauthLoginRequest."),
            "mcpServer/resource/read" => root.Deserialize<McpServerResourceReadRequest>(options) ?? throw new JsonException("Expected McpServerResourceReadRequest."),
            "mcpServer/tool/call" => root.Deserialize<McpServerToolCallRequest>(options) ?? throw new JsonException("Expected McpServerToolCallRequest."),
            "mcpServerStatus/list" => root.Deserialize<McpServerStatusListRequest>(options) ?? throw new JsonException("Expected McpServerStatusListRequest."),
            "model/list" => root.Deserialize<ModelListRequest>(options) ?? throw new JsonException("Expected ModelListRequest."),
            "modelProvider/capabilities/read" => root.Deserialize<ModelProviderCapabilitiesReadRequest>(options) ?? throw new JsonException("Expected ModelProviderCapabilitiesReadRequest."),
            "permissionProfile/list" => root.Deserialize<PermissionProfileListRequest>(options) ?? throw new JsonException("Expected PermissionProfileListRequest."),
            "plugin/install" => root.Deserialize<PluginInstallRequest>(options) ?? throw new JsonException("Expected PluginInstallRequest."),
            "plugin/installed" => root.Deserialize<PluginInstalledRequest>(options) ?? throw new JsonException("Expected PluginInstalledRequest."),
            "plugin/list" => root.Deserialize<PluginListRequest>(options) ?? throw new JsonException("Expected PluginListRequest."),
            "plugin/read" => root.Deserialize<PluginReadRequest>(options) ?? throw new JsonException("Expected PluginReadRequest."),
            "plugin/reconcile" => root.Deserialize<PluginReconcileRequest>(options) ?? throw new JsonException("Expected PluginReconcileRequest."),
            "plugin/share/checkout" => root.Deserialize<PluginShareCheckoutRequest>(options) ?? throw new JsonException("Expected PluginShareCheckoutRequest."),
            "plugin/share/delete" => root.Deserialize<PluginShareDeleteRequest>(options) ?? throw new JsonException("Expected PluginShareDeleteRequest."),
            "plugin/share/list" => root.Deserialize<PluginShareListRequest>(options) ?? throw new JsonException("Expected PluginShareListRequest."),
            "plugin/share/save" => root.Deserialize<PluginShareSaveRequest>(options) ?? throw new JsonException("Expected PluginShareSaveRequest."),
            "plugin/share/updateTargets" => root.Deserialize<PluginShareUpdateTargetsRequest>(options) ?? throw new JsonException("Expected PluginShareUpdateTargetsRequest."),
            "plugin/skill/read" => root.Deserialize<PluginSkillReadRequest>(options) ?? throw new JsonException("Expected PluginSkillReadRequest."),
            "plugin/uninstall" => root.Deserialize<PluginUninstallRequest>(options) ?? throw new JsonException("Expected PluginUninstallRequest."),
            "review/start" => root.Deserialize<ReviewStartRequest>(options) ?? throw new JsonException("Expected ReviewStartRequest."),
            "skills/config/write" => root.Deserialize<SkillsConfigWriteRequest>(options) ?? throw new JsonException("Expected SkillsConfigWriteRequest."),
            "skills/extraRoots/set" => root.Deserialize<SkillsExtraRootsSetRequest>(options) ?? throw new JsonException("Expected SkillsExtraRootsSetRequest."),
            "skills/list" => root.Deserialize<SkillsListRequest>(options) ?? throw new JsonException("Expected SkillsListRequest."),
            "thread/approveGuardianDeniedAction" => root.Deserialize<ThreadApproveGuardianDeniedActionRequest>(options) ?? throw new JsonException("Expected ThreadApproveGuardianDeniedActionRequest."),
            "thread/archive" => root.Deserialize<ThreadArchiveRequest>(options) ?? throw new JsonException("Expected ThreadArchiveRequest."),
            "thread/compact/start" => root.Deserialize<ThreadCompactStartRequest>(options) ?? throw new JsonException("Expected ThreadCompactStartRequest."),
            "thread/delete" => root.Deserialize<ThreadDeleteRequest>(options) ?? throw new JsonException("Expected ThreadDeleteRequest."),
            "thread/fork" => root.Deserialize<ThreadForkRequest>(options) ?? throw new JsonException("Expected ThreadForkRequest."),
            "thread/goal/clear" => root.Deserialize<ThreadGoalClearRequest>(options) ?? throw new JsonException("Expected ThreadGoalClearRequest."),
            "thread/goal/get" => root.Deserialize<ThreadGoalGetRequest>(options) ?? throw new JsonException("Expected ThreadGoalGetRequest."),
            "thread/goal/set" => root.Deserialize<ThreadGoalSetRequest>(options) ?? throw new JsonException("Expected ThreadGoalSetRequest."),
            "thread/inject_items" => root.Deserialize<ThreadInjectItemsRequest>(options) ?? throw new JsonException("Expected ThreadInjectItemsRequest."),
            "thread/items/list" => root.Deserialize<ThreadItemsListRequest>(options) ?? throw new JsonException("Expected ThreadItemsListRequest."),
            "thread/list" => root.Deserialize<ThreadListRequest>(options) ?? throw new JsonException("Expected ThreadListRequest."),
            "thread/loaded/list" => root.Deserialize<ThreadLoadedListRequest>(options) ?? throw new JsonException("Expected ThreadLoadedListRequest."),
            "thread/metadata/update" => root.Deserialize<ThreadMetadataUpdateRequest>(options) ?? throw new JsonException("Expected ThreadMetadataUpdateRequest."),
            "thread/name/set" => root.Deserialize<ThreadNameSetRequest>(options) ?? throw new JsonException("Expected ThreadNameSetRequest."),
            "thread/read" => root.Deserialize<ThreadReadRequest>(options) ?? throw new JsonException("Expected ThreadReadRequest."),
            "thread/resume" => root.Deserialize<ThreadResumeRequest>(options) ?? throw new JsonException("Expected ThreadResumeRequest."),
            "thread/revert" => root.Deserialize<ThreadRevertRequest>(options) ?? throw new JsonException("Expected ThreadRevertRequest."),
            "thread/rollback" => root.Deserialize<ThreadRollbackRequest>(options) ?? throw new JsonException("Expected ThreadRollbackRequest."),
            "thread/section/move" => root.Deserialize<ThreadSectionMoveRequest>(options) ?? throw new JsonException("Expected ThreadSectionMoveRequest."),
            "thread/shellCommand" => root.Deserialize<ThreadShellCommandRequest>(options) ?? throw new JsonException("Expected ThreadShellCommandRequest."),
            "thread/start" => root.Deserialize<ThreadStartRequest>(options) ?? throw new JsonException("Expected ThreadStartRequest."),
            "thread/turns/list" => root.Deserialize<ThreadTurnsListRequest>(options) ?? throw new JsonException("Expected ThreadTurnsListRequest."),
            "thread/unarchive" => root.Deserialize<ThreadUnarchiveRequest>(options) ?? throw new JsonException("Expected ThreadUnarchiveRequest."),
            "thread/unsubscribe" => root.Deserialize<ThreadUnsubscribeRequest>(options) ?? throw new JsonException("Expected ThreadUnsubscribeRequest."),
            "threadSection/create" => root.Deserialize<ThreadSectionCreateRequest>(options) ?? throw new JsonException("Expected ThreadSectionCreateRequest."),
            "threadSection/delete" => root.Deserialize<ThreadSectionDeleteRequest>(options) ?? throw new JsonException("Expected ThreadSectionDeleteRequest."),
            "threadSection/list" => root.Deserialize<ThreadSectionListRequest>(options) ?? throw new JsonException("Expected ThreadSectionListRequest."),
            "threadSection/update" => root.Deserialize<ThreadSectionUpdateRequest>(options) ?? throw new JsonException("Expected ThreadSectionUpdateRequest."),
            "turn/interrupt" => root.Deserialize<TurnInterruptRequest>(options) ?? throw new JsonException("Expected TurnInterruptRequest."),
            "turn/start" => root.Deserialize<TurnStartRequest>(options) ?? throw new JsonException("Expected TurnStartRequest."),
            "turn/steer" => root.Deserialize<TurnSteerRequest>(options) ?? throw new JsonException("Expected TurnSteerRequest."),
            "windowsSandbox/readiness" => root.Deserialize<WindowsSandboxReadinessRequest>(options) ?? throw new JsonException("Expected WindowsSandboxReadinessRequest."),
            "windowsSandbox/setupStart" => root.Deserialize<WindowsSandboxSetupStartRequest>(options) ?? throw new JsonException("Expected WindowsSandboxSetupStartRequest."),
            _ => throw new JsonException("Unknown ClientRequest method \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ClientRequest value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case AccountLoginCancelRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountLoginStartRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountLogoutRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountRateLimitResetCreditConsumeRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountRateLimitsReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountSendAddCreditsNudgeEmailRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountUsageReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AccountWorkspaceMessagesReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AppInstalledRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AppListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case AppReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case CommandExecRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case CommandExecResizeRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case CommandExecTerminateRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case CommandExecWriteRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ConfigBatchWriteRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ConfigMcpServerReloadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ConfigReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ConfigValueWriteRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ConfigRequirementsReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ExperimentalFeatureEnablementSetRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ExperimentalFeatureListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ExternalAgentConfigDetectRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ExternalAgentConfigImportRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ExternalAgentConfigImportReadHistoriesRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ExternalAgentConfigImportRecordHistoryRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FeedbackUploadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsCopyRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsCreateDirectoryRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsGetMetadataRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsReadDirectoryRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsReadFileRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsRemoveRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsUnwatchRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsWatchRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FsWriteFileRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FuzzyFileSearchRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case HooksListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case InitializeRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case MarketplaceAddRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case MarketplaceRemoveRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case MarketplaceUpgradeRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case McpServerOauthLoginRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case McpServerResourceReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case McpServerToolCallRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case McpServerStatusListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ModelListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ModelProviderCapabilitiesReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PermissionProfileListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginInstallRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginInstalledRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginReconcileRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginShareCheckoutRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginShareDeleteRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginShareListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginShareSaveRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginShareUpdateTargetsRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginSkillReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PluginUninstallRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ReviewStartRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case SkillsConfigWriteRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case SkillsExtraRootsSetRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case SkillsListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadApproveGuardianDeniedActionRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadArchiveRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadCompactStartRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadDeleteRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadForkRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadGoalClearRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadGoalGetRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadGoalSetRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadInjectItemsRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadItemsListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadLoadedListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadMetadataUpdateRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadNameSetRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadReadRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadResumeRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadRevertRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadRollbackRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadSectionMoveRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadShellCommandRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadStartRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadTurnsListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadUnarchiveRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadUnsubscribeRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadSectionCreateRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadSectionDeleteRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadSectionListRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ThreadSectionUpdateRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case TurnInterruptRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case TurnStartRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case TurnSteerRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WindowsSandboxReadinessRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WindowsSandboxSetupStartRequest concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ClientRequest.");
        }
    }
}
