// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     This translation layer make sure that we expose codex error code in camel case.
///     
///     When an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.
/// </summary>
[JsonConverter(typeof(CodexErrorInfoJsonConverter))]
public abstract class CodexErrorInfo
{
    private protected CodexErrorInfo() { }
}
