// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexErrorInfoUsageLimitExceededJsonConverter))]
public class CodexErrorInfoUsageLimitExceeded : CodexErrorInfo
{
}
