// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CodexErrorInfoRateLimitExceededJsonConverter : JsonConverter<CodexErrorInfoRateLimitExceeded>
{
    public override CodexErrorInfoRateLimitExceeded Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<CodexErrorInfo>(ref reader, options) as CodexErrorInfoRateLimitExceeded ?? throw new JsonException("Expected CodexErrorInfoRateLimitExceeded.");
    public override void Write(Utf8JsonWriter writer, CodexErrorInfoRateLimitExceeded concrete, JsonSerializerOptions options)
    {
        writer.WriteStringValue("rateLimitExceeded");
    }
}
