// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexErrorInfoMisalignmentPolicyViolationJsonConverter))]
public class CodexErrorInfoMisalignmentPolicyViolation : CodexErrorInfo
{
}
