// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexErrorInfoOtherJsonConverter))]
public class CodexErrorInfoOther : CodexErrorInfo
{
}
