// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexErrorInfoSandboxErrorJsonConverter))]
public class CodexErrorInfoSandboxError : CodexErrorInfo
{
}
