// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexErrorInfoSessionBudgetExceededJsonConverter))]
public class CodexErrorInfoSessionBudgetExceeded : CodexErrorInfo
{
}
