// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CodexErrorInfoInternalServerErrorJsonConverter : JsonConverter<CodexErrorInfoInternalServerError>
{
    public override CodexErrorInfoInternalServerError Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<CodexErrorInfo>(ref reader, options) as CodexErrorInfoInternalServerError ?? throw new JsonException("Expected CodexErrorInfoInternalServerError.");
    public override void Write(Utf8JsonWriter writer, CodexErrorInfoInternalServerError concrete, JsonSerializerOptions options)
    {
        writer.WriteStringValue("internalServerError");
    }
}
