// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexErrorInfoThreadRollbackFailedJsonConverter))]
public class CodexErrorInfoThreadRollbackFailed : CodexErrorInfo
{
}
