// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexResponseHandoffModeJsonConverter))]
public enum CodexResponseHandoffMode
{
    BemTags,
    Commentary,
    Thinking,
}
