// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CodexErrorInfoCyberPolicyJsonConverter))]
public class CodexErrorInfoCyberPolicy : CodexErrorInfo
{
}
