// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CodexErrorInfoSessionBudgetExceededJsonConverter : JsonConverter<CodexErrorInfoSessionBudgetExceeded>
{
    public override CodexErrorInfoSessionBudgetExceeded Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<CodexErrorInfo>(ref reader, options) as CodexErrorInfoSessionBudgetExceeded ?? throw new JsonException("Expected CodexErrorInfoSessionBudgetExceeded.");
    public override void Write(Utf8JsonWriter writer, CodexErrorInfoSessionBudgetExceeded concrete, JsonSerializerOptions options)
    {
        writer.WriteStringValue("sessionBudgetExceeded");
    }
}
