// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CodexResponseHandoffModeJsonConverter : JsonConverter<CodexResponseHandoffMode>
{
    private static CodexResponseHandoffMode Parse(string? value) => value switch
    {
        "bemTags" => CodexResponseHandoffMode.BemTags,
        "commentary" => CodexResponseHandoffMode.Commentary,
        "thinking" => CodexResponseHandoffMode.Thinking,
        _ => throw new JsonException("Unknown CodexResponseHandoffMode value: " + value)
    };
    private static string Format(CodexResponseHandoffMode value) => value switch
    {
        CodexResponseHandoffMode.BemTags => "bemTags",
        CodexResponseHandoffMode.Commentary => "commentary",
        CodexResponseHandoffMode.Thinking => "thinking",
        _ => throw new JsonException("Unknown CodexResponseHandoffMode value: " + value)
    };
    public override CodexResponseHandoffMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for CodexResponseHandoffMode.");
    public override void Write(Utf8JsonWriter writer, CodexResponseHandoffMode value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override CodexResponseHandoffMode ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, CodexResponseHandoffMode value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
