// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CodexErrorInfoContextWindowExceededJsonConverter : JsonConverter<CodexErrorInfoContextWindowExceeded>
{
    public override CodexErrorInfoContextWindowExceeded Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<CodexErrorInfo>(ref reader, options) as CodexErrorInfoContextWindowExceeded ?? throw new JsonException("Expected CodexErrorInfoContextWindowExceeded.");
    public override void Write(Utf8JsonWriter writer, CodexErrorInfoContextWindowExceeded concrete, JsonSerializerOptions options)
    {
        writer.WriteStringValue("contextWindowExceeded");
    }
}
