// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CollabAgentToolJsonConverter))]
public enum CollabAgentTool
{
    CloseAgent,
    FollowupTask,
    InterruptAgent,
    ListAgents,
    ResumeAgent,
    SendInput,
    SendMessage,
    SpawnAgent,
    Wait,
}
