// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CollabAgentToolCallThreadItem : ThreadItem
{
    /// <summary>
    ///     Last known status of the target agents, when available.
    /// </summary>
    [JsonPropertyName("agentsStates")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public Dictionary<string, CollabAgentState> AgentsStates { get; set; } = default!;

    /// <summary>
    ///     Unique identifier for this collab tool call.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    /// <summary>
    ///     Model requested for the spawned agent, when applicable.
    /// </summary>
    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Model { get; set; }

    /// <summary>
    ///     Prompt text sent as part of the collab tool call, when available.
    /// </summary>
    [JsonPropertyName("prompt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Prompt { get; set; }

    /// <summary>
    ///     Reasoning effort requested for the spawned agent, when applicable.
    /// </summary>
    [JsonPropertyName("reasoningEffort")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ReasoningEffort { get; set; }

    /// <summary>
    ///     Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.
    /// </summary>
    [JsonPropertyName("receiverThreadIds")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> ReceiverThreadIds { get; set; } = default!;

    /// <summary>
    ///     Thread ID of the agent issuing the collab request.
    /// </summary>
    [JsonPropertyName("senderThreadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string SenderThreadId { get; set; } = default!;

    /// <summary>
    ///     Current status of the collab tool call.
    /// </summary>
    [JsonPropertyName("status")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CollabAgentToolCallStatus Status { get; set; } = default!;

    /// <summary>
    ///     Name of the collab tool that was invoked.
    /// </summary>
    [JsonPropertyName("tool")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CollabAgentTool Tool { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "collabAgentToolCall";
        private set
        {
            if (value != "collabAgentToolCall")
            {
                throw new JsonException("Expected CollabAgentToolCallThreadItem.type to be collabAgentToolCall.");
            }
        }
    }

}
