// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Collaboration mode for a Codex session.
/// </summary>
public class CollaborationMode
{
    [JsonPropertyName("mode")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ModeKind Mode { get; set; } = default!;

    [JsonPropertyName("settings")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public Settings Settings { get; set; } = default!;

}
