// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CommandExecOutputStreamJsonConverter : JsonConverter<CommandExecOutputStream>
{
    private static CommandExecOutputStream Parse(string? value) => value switch
    {
        "stderr" => CommandExecOutputStream.Stderr,
        "stdout" => CommandExecOutputStream.Stdout,
        _ => throw new JsonException("Unknown CommandExecOutputStream value: " + value)
    };
    private static string Format(CommandExecOutputStream value) => value switch
    {
        CommandExecOutputStream.Stderr => "stderr",
        CommandExecOutputStream.Stdout => "stdout",
        _ => throw new JsonException("Unknown CommandExecOutputStream value: " + value)
    };
    public override CommandExecOutputStream Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for CommandExecOutputStream.");
    public override void Write(Utf8JsonWriter writer, CommandExecOutputStream value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override CommandExecOutputStream ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, CommandExecOutputStream value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
