// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Write stdin bytes to a running `command/exec` session or close stdin.
/// </summary>
public class CommandExecWriteRequest : ClientRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "command/exec/write";
        private set
        {
            if (value != "command/exec/write")
            {
                throw new JsonException("Expected CommandExecWriteRequest.method to be command/exec/write.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CommandExecWriteParams Params { get; set; } = default!;

}
