// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CommandExecutionSourceJsonConverter))]
public enum CommandExecutionSource
{
    Agent,
    UnifiedExecInteraction,
    UnifiedExecStartup,
    UserShell,
}
