// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CommandExecutionApprovalKindJsonConverter : JsonConverter<CommandExecutionApprovalKind>
{
    private static CommandExecutionApprovalKind Parse(string? value) => value switch
    {
        "command" => CommandExecutionApprovalKind.Command,
        "writeStdin" => CommandExecutionApprovalKind.WriteStdin,
        _ => throw new JsonException("Unknown CommandExecutionApprovalKind value: " + value)
    };
    private static string Format(CommandExecutionApprovalKind value) => value switch
    {
        CommandExecutionApprovalKind.Command => "command",
        CommandExecutionApprovalKind.WriteStdin => "writeStdin",
        _ => throw new JsonException("Unknown CommandExecutionApprovalKind value: " + value)
    };
    public override CommandExecutionApprovalKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for CommandExecutionApprovalKind.");
    public override void Write(Utf8JsonWriter writer, CommandExecutionApprovalKind value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override CommandExecutionApprovalKind ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, CommandExecutionApprovalKind value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
