// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CommandExecutionStatusJsonConverter : JsonConverter<CommandExecutionStatus>
{
    private static CommandExecutionStatus Parse(string? value) => value switch
    {
        "completed" => CommandExecutionStatus.Completed,
        "declined" => CommandExecutionStatus.Declined,
        "failed" => CommandExecutionStatus.Failed,
        "inProgress" => CommandExecutionStatus.InProgress,
        _ => throw new JsonException("Unknown CommandExecutionStatus value: " + value)
    };
    private static string Format(CommandExecutionStatus value) => value switch
    {
        CommandExecutionStatus.Completed => "completed",
        CommandExecutionStatus.Declined => "declined",
        CommandExecutionStatus.Failed => "failed",
        CommandExecutionStatus.InProgress => "inProgress",
        _ => throw new JsonException("Unknown CommandExecutionStatus value: " + value)
    };
    public override CommandExecutionStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for CommandExecutionStatus.");
    public override void Write(Utf8JsonWriter writer, CommandExecutionStatus value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override CommandExecutionStatus ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, CommandExecutionStatus value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
