// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(CommandExecutionStatusJsonConverter))]
public enum CommandExecutionStatus
{
    Completed,
    Declined,
    Failed,
    InProgress,
}
