// <auto-generated />
#nullable enable

namespace ZYC.Codex.Protocol;

/// <summary>
///     Empty success response for `command/exec/resize`.
/// </summary>
public class CommandExecResizeResponse
{
}
