// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     User approved the command.
/// </summary>
[JsonConverter(typeof(CommandExecutionApprovalDecisionAcceptJsonConverter))]
public class CommandExecutionApprovalDecisionAccept : CommandExecutionApprovalDecision
{
}
