// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CommandExecutionThreadItem : ThreadItem
{
    /// <summary>
    ///     The command's output, aggregated from stdout and stderr.
    /// </summary>
    [JsonPropertyName("aggregatedOutput")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> AggregatedOutput { get; set; }

    /// <summary>
    ///     The command to be executed.
    /// </summary>
    [JsonPropertyName("command")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Command { get; set; } = default!;

    /// <summary>
    ///     A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.
    /// </summary>
    [JsonPropertyName("commandActions")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<CommandAction> CommandActions { get; set; } = default!;

    /// <summary>
    ///     The command's working directory.
    /// </summary>
    [JsonPropertyName("cwd")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Cwd { get; set; } = default!;

    /// <summary>
    ///     The duration of the command execution in milliseconds.
    /// </summary>
    [JsonPropertyName("durationMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> DurationMs { get; set; }

    /// <summary>
    ///     The command's exit code.
    /// </summary>
    [JsonPropertyName("exitCode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<int?> ExitCode { get; set; }

    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    /// <summary>
    ///     Trusted first-party plugin id when this command resolves to one plugin script.
    /// </summary>
    [JsonPropertyName("pluginId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> PluginId { get; set; }

    /// <summary>
    ///     Identifier for the underlying PTY process (when available).
    /// </summary>
    [JsonPropertyName("processId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ProcessId { get; set; }

    /// <summary>
    ///     Safe plugin-relative path when this command resolves to one plugin script.
    /// </summary>
    [JsonPropertyName("scriptPath")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ScriptPath { get; set; }

    [JsonPropertyName("source")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<CommandExecutionSource> Source { get; set; }

    [JsonPropertyName("status")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CommandExecutionStatus Status { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "commandExecution";
        private set
        {
            if (value != "commandExecution")
            {
                throw new JsonException("Expected CommandExecutionThreadItem.type to be commandExecution.");
            }
        }
    }

}
