// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Distinguishes a command approval from input sent to an existing terminal.
/// </summary>
[JsonConverter(typeof(CommandExecutionApprovalKindJsonConverter))]
public enum CommandExecutionApprovalKind
{
    Command,
    WriteStdin,
}
