// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     User approved the command and future prompts in the same session-scoped approval cache should run without prompting.
/// </summary>
[JsonConverter(typeof(CommandExecutionApprovalDecisionAcceptForSessionJsonConverter))]
public class CommandExecutionApprovalDecisionAcceptForSession : CommandExecutionApprovalDecision
{
}
