// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CommandGuardianApprovalReviewAction : GuardianApprovalReviewAction
{
    [JsonPropertyName("command")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Command { get; set; } = default!;

    [JsonPropertyName("cwd")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Cwd { get; set; } = default!;

    [JsonPropertyName("source")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public GuardianCommandSource Source { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "command";
        private set
        {
            if (value != "command")
            {
                throw new JsonException("Expected CommandGuardianApprovalReviewAction.type to be command.");
            }
        }
    }

}
