// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class CompactionTriggerResponseItem : ResponseItem
{
    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "compaction_trigger";
        private set
        {
            if (value != "compaction_trigger")
            {
                throw new JsonException("Expected CompactionTriggerResponseItem.type to be compaction_trigger.");
            }
        }
    }

}
