// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ConfigWriteResponse
{
    /// <summary>
    ///     Canonical path to the config file that was written.
    /// </summary>
    [JsonPropertyName("filePath")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string FilePath { get; set; } = default!;

    [JsonPropertyName("overriddenMetadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<OverriddenMetadata?> OverriddenMetadata { get; set; }

    [JsonPropertyName("status")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public WriteStatus Status { get; set; } = default!;

    [JsonPropertyName("version")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Version { get; set; } = default!;

}
