// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ConfiguredHookHandlerJsonConverter : JsonConverter<ConfiguredHookHandler>
{
    public override ConfiguredHookHandler Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ConfiguredHookHandler type.");
        return discriminator.GetString() switch
        {
            "agent" => root.Deserialize<AgentConfiguredHookHandler>(options) ?? throw new JsonException("Expected AgentConfiguredHookHandler."),
            "command" => root.Deserialize<CommandConfiguredHookHandler>(options) ?? throw new JsonException("Expected CommandConfiguredHookHandler."),
            "mcp_tool" => root.Deserialize<McpToolConfiguredHookHandler>(options) ?? throw new JsonException("Expected McpToolConfiguredHookHandler."),
            "prompt" => root.Deserialize<PromptConfiguredHookHandler>(options) ?? throw new JsonException("Expected PromptConfiguredHookHandler."),
            _ => throw new JsonException("Unknown ConfiguredHookHandler type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ConfiguredHookHandler value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case AgentConfiguredHookHandler concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case CommandConfiguredHookHandler concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case McpToolConfiguredHookHandler concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PromptConfiguredHookHandler concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ConfiguredHookHandler.");
        }
    }
}
