// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ConfigEdit
{
    [JsonPropertyName("keyPath")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string KeyPath { get; set; } = default!;

    [JsonPropertyName("mergeStrategy")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public MergeStrategy MergeStrategy { get; set; } = default!;

    [JsonPropertyName("value")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public JsonElement Value { get; set; } = default!;

}
