// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ConfigReadResponse
{
    [JsonPropertyName("config")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public Config Config { get; set; } = default!;

    [JsonPropertyName("layers")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<ConfigLayer>?> Layers { get; set; }

    [JsonPropertyName("origins")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public Dictionary<string, ConfigLayerMetadata> Origins { get; set; } = default!;

}
