// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ConfigLayerSourceJsonConverter : JsonConverter<ConfigLayerSource>
{
    public override ConfigLayerSource Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ConfigLayerSource type.");
        return discriminator.GetString() switch
        {
            "enterpriseManaged" => root.Deserialize<EnterpriseManagedConfigLayerSource>(options) ?? throw new JsonException("Expected EnterpriseManagedConfigLayerSource."),
            "legacyManagedConfigTomlFromFile" => root.Deserialize<LegacyManagedConfigTomlFromFileConfigLayerSource>(options) ?? throw new JsonException("Expected LegacyManagedConfigTomlFromFileConfigLayerSource."),
            "legacyManagedConfigTomlFromMdm" => root.Deserialize<LegacyManagedConfigTomlFromMdmConfigLayerSource>(options) ?? throw new JsonException("Expected LegacyManagedConfigTomlFromMdmConfigLayerSource."),
            "mdm" => root.Deserialize<MdmConfigLayerSource>(options) ?? throw new JsonException("Expected MdmConfigLayerSource."),
            "packagedDefaults" => root.Deserialize<PackagedDefaultsConfigLayerSource>(options) ?? throw new JsonException("Expected PackagedDefaultsConfigLayerSource."),
            "project" => root.Deserialize<ProjectConfigLayerSource>(options) ?? throw new JsonException("Expected ProjectConfigLayerSource."),
            "sessionFlags" => root.Deserialize<SessionFlagsConfigLayerSource>(options) ?? throw new JsonException("Expected SessionFlagsConfigLayerSource."),
            "system" => root.Deserialize<SystemConfigLayerSource>(options) ?? throw new JsonException("Expected SystemConfigLayerSource."),
            "user" => root.Deserialize<UserConfigLayerSource>(options) ?? throw new JsonException("Expected UserConfigLayerSource."),
            _ => throw new JsonException("Unknown ConfigLayerSource type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ConfigLayerSource value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case EnterpriseManagedConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case LegacyManagedConfigTomlFromFileConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case LegacyManagedConfigTomlFromMdmConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case MdmConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case PackagedDefaultsConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ProjectConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case SessionFlagsConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case SystemConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case UserConfigLayerSource concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ConfigLayerSource.");
        }
    }
}
