// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ConsumeAccountRateLimitResetCreditParams
{
    /// <summary>
    ///     Opaque reset-credit identifier to redeem. When omitted, the backend selects the next available credit.
    /// </summary>
    [JsonPropertyName("creditId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> CreditId { get; set; }

    /// <summary>
    ///     Identifies one logical reset attempt. A UUID is recommended; reuse the same value when retrying that attempt.
    /// </summary>
    [JsonPropertyName("idempotencyKey")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string IdempotencyKey { get; set; } = default!;

}
