// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ContentItemJsonConverter))]
public abstract class ContentItem
{
    private protected ContentItem() { }
}
