// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ContentItemJsonConverter : JsonConverter<ContentItem>
{
    public override ContentItem Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ContentItem type.");
        return discriminator.GetString() switch
        {
            "input_audio" => root.Deserialize<InputAudioContentItem>(options) ?? throw new JsonException("Expected InputAudioContentItem."),
            "input_image" => root.Deserialize<InputImageContentItem>(options) ?? throw new JsonException("Expected InputImageContentItem."),
            "input_text" => root.Deserialize<InputTextContentItem>(options) ?? throw new JsonException("Expected InputTextContentItem."),
            "output_text" => root.Deserialize<OutputTextContentItem>(options) ?? throw new JsonException("Expected OutputTextContentItem."),
            _ => throw new JsonException("Unknown ContentItem type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ContentItem value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case InputAudioContentItem concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case InputImageContentItem concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case InputTextContentItem concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case OutputTextContentItem concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ContentItem.");
        }
    }
}
