// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ConversationTextRoleJsonConverter : JsonConverter<ConversationTextRole>
{
    private static ConversationTextRole Parse(string? value) => value switch
    {
        "assistant" => ConversationTextRole.Assistant,
        "developer" => ConversationTextRole.Developer,
        "user" => ConversationTextRole.User,
        _ => throw new JsonException("Unknown ConversationTextRole value: " + value)
    };
    private static string Format(ConversationTextRole value) => value switch
    {
        ConversationTextRole.Assistant => "assistant",
        ConversationTextRole.Developer => "developer",
        ConversationTextRole.User => "user",
        _ => throw new JsonException("Unknown ConversationTextRole value: " + value)
    };
    public override ConversationTextRole Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for ConversationTextRole.");
    public override void Write(Utf8JsonWriter writer, ConversationTextRole value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override ConversationTextRole ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, ConversationTextRole value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
