// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class DynamicToolNamespaceToolJsonConverter : JsonConverter<DynamicToolNamespaceTool>
{
    public override DynamicToolNamespaceTool Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid DynamicToolNamespaceTool type.");
        return discriminator.GetString() switch
        {
            "function" => root.Deserialize<FunctionDynamicToolNamespaceTool>(options) ?? throw new JsonException("Expected FunctionDynamicToolNamespaceTool."),
            _ => throw new JsonException("Unknown DynamicToolNamespaceTool type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, DynamicToolNamespaceTool value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case FunctionDynamicToolNamespaceTool concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for DynamicToolNamespaceTool.");
        }
    }
}
