// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class DynamicToolSpecJsonConverter : JsonConverter<DynamicToolSpec>
{
    public override DynamicToolSpec Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid DynamicToolSpec type.");
        return discriminator.GetString() switch
        {
            "function" => root.Deserialize<FunctionDynamicToolSpec>(options) ?? throw new JsonException("Expected FunctionDynamicToolSpec."),
            "namespace" => root.Deserialize<NamespaceDynamicToolSpec>(options) ?? throw new JsonException("Expected NamespaceDynamicToolSpec."),
            _ => throw new JsonException("Unknown DynamicToolSpec type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, DynamicToolSpec value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case FunctionDynamicToolSpec concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case NamespaceDynamicToolSpec concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for DynamicToolSpec.");
        }
    }
}
