// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class DynamicToolCallThreadItem : ThreadItem
{
    [JsonPropertyName("arguments")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public JsonElement Arguments { get; set; } = default!;

    [JsonPropertyName("contentItems")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<DynamicToolCallOutputContentItem>?> ContentItems { get; set; }

    /// <summary>
    ///     The duration of the dynamic tool call in milliseconds.
    /// </summary>
    [JsonPropertyName("durationMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> DurationMs { get; set; }

    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Namespace { get; set; }

    [JsonPropertyName("status")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public DynamicToolCallStatus Status { get; set; } = default!;

    [JsonPropertyName("success")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> Success { get; set; }

    [JsonPropertyName("tool")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Tool { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "dynamicToolCall";
        private set
        {
            if (value != "dynamicToolCall")
            {
                throw new JsonException("Expected DynamicToolCallThreadItem.type to be dynamicToolCall.");
            }
        }
    }

}
