// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class DynamicToolCallOutputContentItemJsonConverter : JsonConverter<DynamicToolCallOutputContentItem>
{
    public override DynamicToolCallOutputContentItem Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid DynamicToolCallOutputContentItem type.");
        return discriminator.GetString() switch
        {
            "inputAudio" => root.Deserialize<InputAudioDynamicToolCallOutputContentItem>(options) ?? throw new JsonException("Expected InputAudioDynamicToolCallOutputContentItem."),
            "inputImage" => root.Deserialize<InputImageDynamicToolCallOutputContentItem>(options) ?? throw new JsonException("Expected InputImageDynamicToolCallOutputContentItem."),
            "inputText" => root.Deserialize<InputTextDynamicToolCallOutputContentItem>(options) ?? throw new JsonException("Expected InputTextDynamicToolCallOutputContentItem."),
            _ => throw new JsonException("Unknown DynamicToolCallOutputContentItem type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, DynamicToolCallOutputContentItem value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case InputAudioDynamicToolCallOutputContentItem concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case InputImageDynamicToolCallOutputContentItem concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case InputTextDynamicToolCallOutputContentItem concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for DynamicToolCallOutputContentItem.");
        }
    }
}
