// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     A path owned by an execution environment.
/// </summary>
public class EnvironmentCapabilityRootLocation : CapabilityRootLocation
{
    [JsonPropertyName("environmentId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string EnvironmentId { get; set; } = default!;

    /// <summary>
    ///     Absolute path for the root in the selected environment.
    /// </summary>
    [JsonPropertyName("path")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Path { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "environment";
        private set
        {
            if (value != "environment")
            {
                throw new JsonException("Expected EnvironmentCapabilityRootLocation.type to be environment.");
            }
        }
    }

}
