// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ErrorNotification
{
    [JsonPropertyName("error")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public TurnError Error { get; set; } = default!;

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

    [JsonPropertyName("turnId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string TurnId { get; set; } = default!;

    [JsonPropertyName("willRetry")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool WillRetry { get; set; } = default!;

}
