// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ExecveGuardianApprovalReviewAction : GuardianApprovalReviewAction
{
    [JsonPropertyName("argv")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> Argv { get; set; } = default!;

    [JsonPropertyName("cwd")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Cwd { get; set; } = default!;

    [JsonPropertyName("program")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Program { get; set; } = default!;

    [JsonPropertyName("source")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public GuardianCommandSource Source { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "execve";
        private set
        {
            if (value != "execve")
            {
                throw new JsonException("Expected ExecveGuardianApprovalReviewAction.type to be execve.");
            }
        }
    }

}
