// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ExperimentalFeature
{
    /// <summary>
    ///     Announcement copy shown to users when the feature is introduced. Null when this feature is not in beta.
    /// </summary>
    [JsonPropertyName("announcement")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Announcement { get; set; }

    /// <summary>
    ///     Whether this feature is enabled by default.
    /// </summary>
    [JsonPropertyName("defaultEnabled")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool DefaultEnabled { get; set; } = default!;

    /// <summary>
    ///     Short summary describing what the feature does. Null when this feature is not in beta.
    /// </summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Description { get; set; }

    /// <summary>
    ///     User-facing display name shown in the experimental features UI. Null when this feature is not in beta.
    /// </summary>
    [JsonPropertyName("displayName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> DisplayName { get; set; }

    /// <summary>
    ///     Whether this feature is currently enabled in the loaded config.
    /// </summary>
    [JsonPropertyName("enabled")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool Enabled { get; set; } = default!;

    /// <summary>
    ///     Stable key used in config.toml and CLI flag toggles.
    /// </summary>
    [JsonPropertyName("name")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Name { get; set; } = default!;

    /// <summary>
    ///     Lifecycle stage of this feature flag.
    /// </summary>
    [JsonPropertyName("stage")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ExperimentalFeatureStage Stage { get; set; } = default!;

}
