// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ExperimentalFeatureEnablementSetParams
{
    /// <summary>
    ///     Process-wide runtime feature enablement keyed by canonical feature name.
    ///     
    ///     Only named features are updated. Omitted features are left unchanged. Send an empty map for a no-op.
    /// </summary>
    [JsonPropertyName("enablement")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public Dictionary<string, bool> Enablement { get; set; } = default!;

}
