// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ExternalAgentDetectedConnectorSourceJsonConverter))]
public enum ExternalAgentDetectedConnectorSource
{
    RemoteMcpServersConfig,
    SessionToolUse,
}
