// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ExternalAgentConfigImportReadHistoriesRequest : ClientRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "externalAgentConfig/import/readHistories";
        private set
        {
            if (value != "externalAgentConfig/import/readHistories")
            {
                throw new JsonException("Expected ExternalAgentConfigImportReadHistoriesRequest.method to be externalAgentConfig/import/readHistories.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ProtocolNull?> Params { get; set; }

}
