// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ExternalAgentConfigMigrationItemTypeJsonConverter : JsonConverter<ExternalAgentConfigMigrationItemType>
{
    private static ExternalAgentConfigMigrationItemType Parse(string? value) => value switch
    {
        "AGENTS_MD" => ExternalAgentConfigMigrationItemType.AGENTSMD,
        "COMMANDS" => ExternalAgentConfigMigrationItemType.COMMANDS,
        "CONFIG" => ExternalAgentConfigMigrationItemType.CONFIG,
        "HOOKS" => ExternalAgentConfigMigrationItemType.HOOKS,
        "MCP_SERVER_CONFIG" => ExternalAgentConfigMigrationItemType.MCPSERVERCONFIG,
        "MEMORY" => ExternalAgentConfigMigrationItemType.MEMORY,
        "PLUGINS" => ExternalAgentConfigMigrationItemType.PLUGINS,
        "SESSIONS" => ExternalAgentConfigMigrationItemType.SESSIONS,
        "SKILLS" => ExternalAgentConfigMigrationItemType.SKILLS,
        "SUBAGENTS" => ExternalAgentConfigMigrationItemType.SUBAGENTS,
        _ => throw new JsonException("Unknown ExternalAgentConfigMigrationItemType value: " + value)
    };
    private static string Format(ExternalAgentConfigMigrationItemType value) => value switch
    {
        ExternalAgentConfigMigrationItemType.AGENTSMD => "AGENTS_MD",
        ExternalAgentConfigMigrationItemType.COMMANDS => "COMMANDS",
        ExternalAgentConfigMigrationItemType.CONFIG => "CONFIG",
        ExternalAgentConfigMigrationItemType.HOOKS => "HOOKS",
        ExternalAgentConfigMigrationItemType.MCPSERVERCONFIG => "MCP_SERVER_CONFIG",
        ExternalAgentConfigMigrationItemType.MEMORY => "MEMORY",
        ExternalAgentConfigMigrationItemType.PLUGINS => "PLUGINS",
        ExternalAgentConfigMigrationItemType.SESSIONS => "SESSIONS",
        ExternalAgentConfigMigrationItemType.SKILLS => "SKILLS",
        ExternalAgentConfigMigrationItemType.SUBAGENTS => "SUBAGENTS",
        _ => throw new JsonException("Unknown ExternalAgentConfigMigrationItemType value: " + value)
    };
    public override ExternalAgentConfigMigrationItemType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for ExternalAgentConfigMigrationItemType.");
    public override void Write(Utf8JsonWriter writer, ExternalAgentConfigMigrationItemType value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override ExternalAgentConfigMigrationItemType ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, ExternalAgentConfigMigrationItemType value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
