// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ExternalAgentConfigImportHistoryRecordTypeResultParams
{
    [JsonPropertyName("failures")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ExternalAgentConfigImportItemTypeFailure> Failures { get; set; } = default!;

    [JsonPropertyName("itemType")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ExternalAgentConfigMigrationItemType ItemType { get; set; } = default!;

    [JsonPropertyName("successes")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ExternalAgentConfigImportHistoryRecordSuccessParams> Successes { get; set; } = default!;

}
