// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ExternalAgentConfigImportRecordHistoryRequest : ClientRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "externalAgentConfig/import/recordHistory";
        private set
        {
            if (value != "externalAgentConfig/import/recordHistory")
            {
                throw new JsonException("Expected ExternalAgentConfigImportRecordHistoryRequest.method to be externalAgentConfig/import/recordHistory.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ExternalAgentConfigImportHistoryRecordParams Params { get; set; } = default!;

}
