// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(FileSystemSpecialPathJsonConverter))]
public abstract class FileSystemSpecialPath
{
    private protected FileSystemSpecialPath() { }
}
