// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class FileSystemSpecialPathJsonConverter : JsonConverter<FileSystemSpecialPath>
{
    public override FileSystemSpecialPath Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("kind", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid FileSystemSpecialPath kind.");
        return discriminator.GetString() switch
        {
            "minimal" => root.Deserialize<MinimalFileSystemSpecialPath>(options) ?? throw new JsonException("Expected MinimalFileSystemSpecialPath."),
            "project_roots" => root.Deserialize<KindFileSystemSpecialPath>(options) ?? throw new JsonException("Expected KindFileSystemSpecialPath."),
            "root" => root.Deserialize<RootFileSystemSpecialPath>(options) ?? throw new JsonException("Expected RootFileSystemSpecialPath."),
            "slash_tmp" => root.Deserialize<SlashTmpFileSystemSpecialPath>(options) ?? throw new JsonException("Expected SlashTmpFileSystemSpecialPath."),
            "tmpdir" => root.Deserialize<TmpdirFileSystemSpecialPath>(options) ?? throw new JsonException("Expected TmpdirFileSystemSpecialPath."),
            "unknown" => root.Deserialize<FileSystemSpecialPathUnknown>(options) ?? throw new JsonException("Expected FileSystemSpecialPathUnknown."),
            _ => throw new JsonException("Unknown FileSystemSpecialPath kind \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, FileSystemSpecialPath value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case MinimalFileSystemSpecialPath concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case KindFileSystemSpecialPath concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case RootFileSystemSpecialPath concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case SlashTmpFileSystemSpecialPath concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case TmpdirFileSystemSpecialPath concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case FileSystemSpecialPathUnknown concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for FileSystemSpecialPath.");
        }
    }
}
