// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class FileSystemSpecialPathUnknown : FileSystemSpecialPath
{
    [JsonPropertyName("kind")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Kind
    {
        get => "unknown";
        private set
        {
            if (value != "unknown")
            {
                throw new JsonException("Expected FileSystemSpecialPathUnknown.kind to be unknown.");
            }
        }
    }

    [JsonPropertyName("path")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Path { get; set; } = default!;

    [JsonPropertyName("subpath")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Subpath { get; set; }

}
