// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ForcedChatgptWorkspaceIdsArrayJsonConverter))]
public class ForcedChatgptWorkspaceIdsArray : ForcedChatgptWorkspaceIds
{
    public List<string> Value { get; set; } = default!;
}
