// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Filesystem watch notification emitted for `fs/watch` subscribers.
/// </summary>
public class FsChangedNotification
{
    /// <summary>
    ///     File or directory paths associated with this event.
    /// </summary>
    [JsonPropertyName("changedPaths")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> ChangedPaths { get; set; } = default!;

    /// <summary>
    ///     Watch identifier previously provided to `fs/watch`.
    /// </summary>
    [JsonPropertyName("watchId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string WatchId { get; set; } = default!;

}
