// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Directory entries returned by `fs/readDirectory`.
/// </summary>
public class FsReadDirectoryResponse
{
    /// <summary>
    ///     Direct child entries in the requested directory.
    /// </summary>
    [JsonPropertyName("entries")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<FsReadDirectoryEntry> Entries { get; set; } = default!;

}
