// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     List direct child names for a directory.
/// </summary>
public class FsReadDirectoryParams
{
    /// <summary>
    ///     Absolute directory path to read.
    /// </summary>
    [JsonPropertyName("path")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Path { get; set; } = default!;

}
