// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Stop filesystem watch notifications for a prior `fs/watch`.
/// </summary>
public class FsUnwatchParams
{
    /// <summary>
    ///     Watch identifier previously provided to `fs/watch`.
    /// </summary>
    [JsonPropertyName("watchId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string WatchId { get; set; } = default!;

}
