// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(FunctionCallOutputBodyArrayJsonConverter))]
public class FunctionCallOutputBodyArray : FunctionCallOutputBody
{
    public List<FunctionCallOutputContentItem> Value { get; set; } = default!;
}
