// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(FunctionCallOutputBodyStringJsonConverter))]
public class FunctionCallOutputBodyString : FunctionCallOutputBody
{
    public string Value { get; set; } = default!;
}
