// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class FunctionCallResponseItem : ResponseItem
{
    [JsonPropertyName("arguments")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Arguments { get; set; } = default!;

    [JsonPropertyName("call_id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string CallId { get; set; } = default!;

    [JsonPropertyName("encrypted_function_args")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>?> EncryptedFunctionArgs { get; set; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Id { get; set; }

    [JsonPropertyName("internal_chat_message_metadata_passthrough")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<InternalChatMessageMetadataPassthrough?> InternalChatMessageMetadataPassthrough { get; set; }

    [JsonPropertyName("name")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Name { get; set; } = default!;

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Namespace { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "function_call";
        private set
        {
            if (value != "function_call")
            {
                throw new JsonException("Expected FunctionCallResponseItem.type to be function_call.");
            }
        }
    }

}
