// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Superset of [`codex_file_search::FileMatch`]
/// </summary>
public class FuzzyFileSearchResult
{
    [JsonPropertyName("file_name")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string FileName { get; set; } = default!;

    [JsonPropertyName("indices")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<uint>?> Indices { get; set; }

    [JsonPropertyName("match_type")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public FuzzyFileSearchMatchType MatchType { get; set; } = default!;

    [JsonPropertyName("path")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Path { get; set; } = default!;

    [JsonPropertyName("root")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Root { get; set; } = default!;

    [JsonPropertyName("score")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public uint Score { get; set; } = default!;

}
