// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class GlobPatternFileSystemPath : FileSystemPath
{
    [JsonPropertyName("pattern")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Pattern { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "glob_pattern";
        private set
        {
            if (value != "glob_pattern")
            {
                throw new JsonException("Expected GlobPatternFileSystemPath.type to be glob_pattern.");
            }
        }
    }

}
