// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(GuardianApprovalReviewActionJsonConverter))]
public abstract class GuardianApprovalReviewAction
{
    private protected GuardianApprovalReviewAction() { }
}
