// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class GuardianApprovalReviewActionJsonConverter : JsonConverter<GuardianApprovalReviewAction>
{
    public override GuardianApprovalReviewAction Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid GuardianApprovalReviewAction type.");
        return discriminator.GetString() switch
        {
            "applyPatch" => root.Deserialize<ApplyPatchGuardianApprovalReviewAction>(options) ?? throw new JsonException("Expected ApplyPatchGuardianApprovalReviewAction."),
            "command" => root.Deserialize<CommandGuardianApprovalReviewAction>(options) ?? throw new JsonException("Expected CommandGuardianApprovalReviewAction."),
            "execve" => root.Deserialize<ExecveGuardianApprovalReviewAction>(options) ?? throw new JsonException("Expected ExecveGuardianApprovalReviewAction."),
            "mcpToolCall" => root.Deserialize<McpToolCallGuardianApprovalReviewAction>(options) ?? throw new JsonException("Expected McpToolCallGuardianApprovalReviewAction."),
            "networkAccess" => root.Deserialize<NetworkAccessGuardianApprovalReviewAction>(options) ?? throw new JsonException("Expected NetworkAccessGuardianApprovalReviewAction."),
            "requestPermissions" => root.Deserialize<RequestPermissionsGuardianApprovalReviewAction>(options) ?? throw new JsonException("Expected RequestPermissionsGuardianApprovalReviewAction."),
            "writeStdin" => root.Deserialize<WriteStdinGuardianApprovalReviewAction>(options) ?? throw new JsonException("Expected WriteStdinGuardianApprovalReviewAction."),
            _ => throw new JsonException("Unknown GuardianApprovalReviewAction type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, GuardianApprovalReviewAction value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case ApplyPatchGuardianApprovalReviewAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case CommandGuardianApprovalReviewAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case ExecveGuardianApprovalReviewAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case McpToolCallGuardianApprovalReviewAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case NetworkAccessGuardianApprovalReviewAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case RequestPermissionsGuardianApprovalReviewAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WriteStdinGuardianApprovalReviewAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for GuardianApprovalReviewAction.");
        }
    }
}
