// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class GuardianWarningNotification
{
    /// <summary>
    ///     Concise guardian warning message for the user.
    /// </summary>
    [JsonPropertyName("message")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Message { get; set; } = default!;

    /// <summary>
    ///     Thread target for the guardian warning.
    /// </summary>
    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
