// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class HookHandlerTypeJsonConverter : JsonConverter<HookHandlerType>
{
    private static HookHandlerType Parse(string? value) => value switch
    {
        "agent" => HookHandlerType.Agent,
        "command" => HookHandlerType.Command,
        "mcpTool" => HookHandlerType.McpTool,
        "prompt" => HookHandlerType.Prompt,
        _ => throw new JsonException("Unknown HookHandlerType value: " + value)
    };
    private static string Format(HookHandlerType value) => value switch
    {
        HookHandlerType.Agent => "agent",
        HookHandlerType.Command => "command",
        HookHandlerType.McpTool => "mcpTool",
        HookHandlerType.Prompt => "prompt",
        _ => throw new JsonException("Unknown HookHandlerType value: " + value)
    };
    public override HookHandlerType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for HookHandlerType.");
    public override void Write(Utf8JsonWriter writer, HookHandlerType value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override HookHandlerType ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, HookHandlerType value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
