// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class HooksListParams
{
    /// <summary>
    ///     When empty, defaults to the current session working directory.
    /// </summary>
    [JsonPropertyName("cwds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>> Cwds { get; set; }

}
