// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class HookSourceJsonConverter : JsonConverter<HookSource>
{
    private static HookSource Parse(string? value) => value switch
    {
        "cloudManagedConfig" => HookSource.CloudManagedConfig,
        "cloudRequirements" => HookSource.CloudRequirements,
        "legacyManagedConfigFile" => HookSource.LegacyManagedConfigFile,
        "legacyManagedConfigMdm" => HookSource.LegacyManagedConfigMdm,
        "mdm" => HookSource.Mdm,
        "plugin" => HookSource.Plugin,
        "project" => HookSource.Project,
        "sessionFlags" => HookSource.SessionFlags,
        "system" => HookSource.System,
        "unknown" => HookSource.Unknown,
        "user" => HookSource.User,
        _ => throw new JsonException("Unknown HookSource value: " + value)
    };
    private static string Format(HookSource value) => value switch
    {
        HookSource.CloudManagedConfig => "cloudManagedConfig",
        HookSource.CloudRequirements => "cloudRequirements",
        HookSource.LegacyManagedConfigFile => "legacyManagedConfigFile",
        HookSource.LegacyManagedConfigMdm => "legacyManagedConfigMdm",
        HookSource.Mdm => "mdm",
        HookSource.Plugin => "plugin",
        HookSource.Project => "project",
        HookSource.SessionFlags => "sessionFlags",
        HookSource.System => "system",
        HookSource.Unknown => "unknown",
        HookSource.User => "user",
        _ => throw new JsonException("Unknown HookSource value: " + value)
    };
    public override HookSource Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for HookSource.");
    public override void Write(Utf8JsonWriter writer, HookSource value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override HookSource ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, HookSource value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
