// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class HookScopeJsonConverter : JsonConverter<HookScope>
{
    private static HookScope Parse(string? value) => value switch
    {
        "thread" => HookScope.Thread,
        "turn" => HookScope.Turn,
        _ => throw new JsonException("Unknown HookScope value: " + value)
    };
    private static string Format(HookScope value) => value switch
    {
        HookScope.Thread => "thread",
        HookScope.Turn => "turn",
        _ => throw new JsonException("Unknown HookScope value: " + value)
    };
    public override HookScope Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for HookScope.");
    public override void Write(Utf8JsonWriter writer, HookScope value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override HookScope ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, HookScope value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
