// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class HookMetadataMcpTool : HookMetadata
{
    /// <summary>
    ///     Configured `additionalContext` spill threshold. `null` uses 2,500 tokens; `0` disables spilling.
    /// </summary>
    [JsonPropertyName("additionalContextLimit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ulong?> AdditionalContextLimit { get; set; }

    [JsonPropertyName("currentHash")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string CurrentHash { get; set; } = default!;

    [JsonPropertyName("displayOrder")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public long DisplayOrder { get; set; } = default!;

    [JsonPropertyName("enabled")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool Enabled { get; set; } = default!;

    [JsonPropertyName("eventName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public HookEventName EventName { get; set; } = default!;

    [JsonPropertyName("handlerType")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string HandlerType
    {
        get => "mcpTool";
        private set
        {
            if (value != "mcpTool")
            {
                throw new JsonException("Expected HookMetadataMcpTool.handlerType to be mcpTool.");
            }
        }
    }

    [JsonPropertyName("isManaged")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool IsManaged { get; set; } = default!;

    [JsonPropertyName("key")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Key { get; set; } = default!;

    [JsonPropertyName("matcher")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Matcher { get; set; }

    [JsonPropertyName("pluginId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> PluginId { get; set; }

    [JsonPropertyName("server")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Server { get; set; } = default!;

    [JsonPropertyName("source")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public HookSource Source { get; set; } = default!;

    [JsonPropertyName("sourcePath")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string SourcePath { get; set; } = default!;

    [JsonPropertyName("statusMessage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> StatusMessage { get; set; }

    [JsonPropertyName("timeoutSec")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ulong TimeoutSec { get; set; } = default!;

    [JsonPropertyName("tool")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Tool { get; set; } = default!;

    [JsonPropertyName("trustStatus")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public HookTrustStatus TrustStatus { get; set; } = default!;

}
