// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(HookTrustStatusJsonConverter))]
public enum HookTrustStatus
{
    Managed,
    Modified,
    Trusted,
    Untrusted,
}
