// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ImageGenerationFailureJsonConverter : JsonConverter<ImageGenerationFailure>
{
    public override ImageGenerationFailure Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ImageGenerationFailure type.");
        return discriminator.GetString() switch
        {
            "usageLimitExceeded" => root.Deserialize<UsageLimitExceededImageGenerationFailure>(options) ?? throw new JsonException("Expected UsageLimitExceededImageGenerationFailure."),
            _ => throw new JsonException("Unknown ImageGenerationFailure type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ImageGenerationFailure value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case UsageLimitExceededImageGenerationFailure concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ImageGenerationFailure.");
        }
    }
}
