// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class InlineVisualizationThreadRealtimeBemItemPresentation : ThreadRealtimeBemItemPresentation
{
    [JsonPropertyName("index")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public uint Index { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "inlineVisualization";
        private set
        {
            if (value != "inlineVisualization")
            {
                throw new JsonException("Expected InlineVisualizationThreadRealtimeBemItemPresentation.type to be inlineVisualization.");
            }
        }
    }

}
