// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class InputTextDynamicToolCallOutputContentItem : DynamicToolCallOutputContentItem
{
    [JsonPropertyName("text")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Text { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "inputText";
        private set
        {
            if (value != "inputText")
            {
                throw new JsonException("Expected InputTextDynamicToolCallOutputContentItem.type to be inputText.");
            }
        }
    }

}
