// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Canonical user-input modality tags advertised by a model.
/// </summary>
[JsonConverter(typeof(InputModalityJsonConverter))]
public enum InputModality
{
    Audio,
    Image,
    Text,
}
