// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class InputTextFunctionCallOutputContentItem : FunctionCallOutputContentItem
{
    [JsonPropertyName("text")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Text { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "input_text";
        private set
        {
            if (value != "input_text")
            {
                throw new JsonException("Expected InputTextFunctionCallOutputContentItem.type to be input_text.");
            }
        }
    }

}
