// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class InputAudioFunctionCallOutputContentItem : FunctionCallOutputContentItem
{
    [JsonPropertyName("audio_url")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string AudioUrl { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "input_audio";
        private set
        {
            if (value != "input_audio")
            {
                throw new JsonException("Expected InputAudioFunctionCallOutputContentItem.type to be input_audio.");
            }
        }
    }

}
