// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class InputImageDynamicToolCallOutputContentItem : DynamicToolCallOutputContentItem
{
    [JsonPropertyName("imageUrl")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ImageUrl { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "inputImage";
        private set
        {
            if (value != "inputImage")
            {
                throw new JsonException("Expected InputImageDynamicToolCallOutputContentItem.type to be inputImage.");
            }
        }
    }

}
