// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     [UNSTABLE] Temporary notification payload for approval auto-review. This shape is expected to change soon.
/// </summary>
public class ItemGuardianApprovalReviewCompletedNotification
{
    [JsonPropertyName("action")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public GuardianApprovalReviewAction Action { get; set; } = default!;

    /// <summary>
    ///     Unix timestamp (in milliseconds) when this review completed.
    /// </summary>
    [JsonPropertyName("completedAtMs")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public long CompletedAtMs { get; set; } = default!;

    [JsonPropertyName("decisionSource")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string DecisionSource
    {
        get => "agent";
        private set
        {
            if (value != "agent")
            {
                throw new JsonException("Expected ItemGuardianApprovalReviewCompletedNotification.decisionSource to be agent.");
            }
        }
    }

    [JsonPropertyName("review")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public GuardianApprovalReview Review { get; set; } = default!;

    /// <summary>
    ///     Stable identifier for this review.
    /// </summary>
    [JsonPropertyName("reviewId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ReviewId { get; set; } = default!;

    /// <summary>
    ///     Unix timestamp (in milliseconds) when this review started.
    /// </summary>
    [JsonPropertyName("startedAtMs")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public long StartedAtMs { get; set; } = default!;

    /// <summary>
    ///     Identifier for the reviewed item or tool call when one exists.
    ///     
    ///     In most cases, one review maps to one target item. The exceptions are - execve reviews, where a single command may contain multiple execve calls to review (only possible when using the shell_zsh_fork feature) - stdin reviews, which refer to the existing parent command item and have a separate approval ID in the action payload - network policy reviews, where there is no target item
    ///     
    ///     A network call is triggered by a CommandExecution item, so having a target_item_id set to the CommandExecution item would be misleading because the review is about the network call, not the command execution. Therefore, target_item_id is set to None for network policy reviews.
    /// </summary>
    [JsonPropertyName("targetItemId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> TargetItemId { get; set; }

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

    [JsonPropertyName("turnId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string TurnId { get; set; } = default!;

}
