// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     NEW APIs Sent when approval is requested for a specific command execution. This request is used for Turns started via turn/start.
/// </summary>
public class ItemCommandExecutionRequestApprovalRequest : ServerRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "item/commandExecution/requestApproval";
        private set
        {
            if (value != "item/commandExecution/requestApproval")
            {
                throw new JsonException("Expected ItemCommandExecutionRequestApprovalRequest.method to be item/commandExecution/requestApproval.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CommandExecutionRequestApprovalParams Params { get; set; } = default!;

}
