// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Request approval for additional permissions from the user.
/// </summary>
public class ItemPermissionsRequestApprovalRequest : ServerRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "item/permissions/requestApproval";
        private set
        {
            if (value != "item/permissions/requestApproval")
            {
                throw new JsonException("Expected ItemPermissionsRequestApprovalRequest.method to be item/permissions/requestApproval.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PermissionsRequestApprovalParams Params { get; set; } = default!;

}
