// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL - proposed plan streaming deltas for plan items.
/// </summary>
public class ItemPlanDeltaNotification : ServerNotification
{
    /// <summary>
    ///     Unix timestamp (in milliseconds) when app-server emitted this notification.
    /// </summary>
    [JsonPropertyName("emittedAtMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long> EmittedAtMs { get; set; }

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "item/plan/delta";
        private set
        {
            if (value != "item/plan/delta")
            {
                throw new JsonException("Expected ItemPlanDeltaNotification.method to be item/plan/delta.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PlanDeltaNotification Params { get; set; } = default!;

}
