// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class JSONRPCMessageJSONRPCNotificationJsonConverter : JsonConverter<JSONRPCMessageJSONRPCNotification>
{
    public override JSONRPCMessageJSONRPCNotification Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<JSONRPCMessage>(ref reader, options) as JSONRPCMessageJSONRPCNotification ?? throw new JsonException("Expected JSONRPCMessageJSONRPCNotification.");
    public override void Write(Utf8JsonWriter writer, JSONRPCMessageJSONRPCNotification concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
