// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class LegacyManagedConfigTomlFromMdmConfigLayerSource : ConfigLayerSource
{
    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "legacyManagedConfigTomlFromMdm";
        private set
        {
            if (value != "legacyManagedConfigTomlFromMdm")
            {
                throw new JsonException("Expected LegacyManagedConfigTomlFromMdmConfigLayerSource.type to be legacyManagedConfigTomlFromMdm.");
            }
        }
    }

}
