// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ListFilesParsedCommand : ParsedCommand
{
    [JsonPropertyName("cmd")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Cmd { get; set; } = default!;

    [JsonPropertyName("path")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Path { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "list_files";
        private set
        {
            if (value != "list_files")
            {
                throw new JsonException("Expected ListFilesParsedCommand.type to be list_files.");
            }
        }
    }

}
