// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(LocalShellActionJsonConverter))]
public abstract class LocalShellAction
{
    private protected LocalShellAction() { }
}
