// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class MarketplaceUpgradeErrorInfo
{
    [JsonPropertyName("marketplaceName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string MarketplaceName { get; set; } = default!;

    [JsonPropertyName("message")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Message { get; set; } = default!;

}
