// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class MarketplaceUpgradeResponse
{
    [JsonPropertyName("errors")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<MarketplaceUpgradeErrorInfo> Errors { get; set; } = default!;

    [JsonPropertyName("selectedMarketplaces")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> SelectedMarketplaces { get; set; } = default!;

    [JsonPropertyName("upgradedRoots")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> UpgradedRoots { get; set; } = default!;

}
