// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class MarketplaceAddRequest : ClientRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "marketplace/add";
        private set
        {
            if (value != "marketplace/add")
            {
                throw new JsonException("Expected MarketplaceAddRequest.method to be marketplace/add.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public MarketplaceAddParams Params { get; set; } = default!;

}
