// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpAuthStatusJsonConverter : JsonConverter<McpAuthStatus>
{
    private static McpAuthStatus Parse(string? value) => value switch
    {
        "bearerToken" => McpAuthStatus.BearerToken,
        "notLoggedIn" => McpAuthStatus.NotLoggedIn,
        "oAuth" => McpAuthStatus.OAuth,
        "unknown" => McpAuthStatus.Unknown,
        "unsupported" => McpAuthStatus.Unsupported,
        _ => throw new JsonException("Unknown McpAuthStatus value: " + value)
    };
    private static string Format(McpAuthStatus value) => value switch
    {
        McpAuthStatus.BearerToken => "bearerToken",
        McpAuthStatus.NotLoggedIn => "notLoggedIn",
        McpAuthStatus.OAuth => "oAuth",
        McpAuthStatus.Unknown => "unknown",
        McpAuthStatus.Unsupported => "unsupported",
        _ => throw new JsonException("Unknown McpAuthStatus value: " + value)
    };
    public override McpAuthStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for McpAuthStatus.");
    public override void Write(Utf8JsonWriter writer, McpAuthStatus value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override McpAuthStatus ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, McpAuthStatus value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
