// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpElicitationPrimitiveSchemaMcpElicitationTitledSingleSelectEnumSchemaJsonConverter))]
public class McpElicitationPrimitiveSchemaMcpElicitationTitledSingleSelectEnumSchema : McpElicitationPrimitiveSchema
{
    public McpElicitationTitledSingleSelectEnumSchema Value { get; set; } = default!;
}
