// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpElicitationPrimitiveSchemaMcpElicitationBooleanSchemaJsonConverter : JsonConverter<McpElicitationPrimitiveSchemaMcpElicitationBooleanSchema>
{
    public override McpElicitationPrimitiveSchemaMcpElicitationBooleanSchema Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<McpElicitationPrimitiveSchema>(ref reader, options) as McpElicitationPrimitiveSchemaMcpElicitationBooleanSchema ?? throw new JsonException("Expected McpElicitationPrimitiveSchemaMcpElicitationBooleanSchema.");
    public override void Write(Utf8JsonWriter writer, McpElicitationPrimitiveSchemaMcpElicitationBooleanSchema concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
