// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchemaJsonConverter))]
public class McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchema : McpElicitationEnumSchema
{
    public McpElicitationTitledSingleSelectEnumSchema Value { get; set; } = default!;
}
