// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchemaJsonConverter : JsonConverter<McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchema>
{
    public override McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchema Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<McpElicitationEnumSchema>(ref reader, options) as McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchema ?? throw new JsonException("Expected McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchema.");
    public override void Write(Utf8JsonWriter writer, McpElicitationEnumSchemaMcpElicitationTitledSingleSelectEnumSchema concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
