// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpElicitationPrimitiveSchemaMcpElicitationUntitledMultiSelectEnumSchemaJsonConverter))]
public class McpElicitationPrimitiveSchemaMcpElicitationUntitledMultiSelectEnumSchema : McpElicitationPrimitiveSchema
{
    public McpElicitationUntitledMultiSelectEnumSchema Value { get; set; } = default!;
}
