// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpElicitationPrimitiveSchemaMcpElicitationBooleanSchemaJsonConverter))]
public class McpElicitationPrimitiveSchemaMcpElicitationBooleanSchema : McpElicitationPrimitiveSchema
{
    public McpElicitationBooleanSchema Value { get; set; } = default!;
}
