// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpElicitationEnumSchemaMcpElicitationLegacyTitledEnumSchemaJsonConverter))]
public class McpElicitationEnumSchemaMcpElicitationLegacyTitledEnumSchema : McpElicitationEnumSchema
{
    public McpElicitationLegacyTitledEnumSchema Value { get; set; } = default!;
}
