// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpElicitationSingleSelectEnumSchemaMcpElicitationTitledSingleSelectEnumSchemaJsonConverter))]
public class McpElicitationSingleSelectEnumSchemaMcpElicitationTitledSingleSelectEnumSchema : McpElicitationSingleSelectEnumSchema
{
    public McpElicitationTitledSingleSelectEnumSchema Value { get; set; } = default!;
}
