// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpElicitationPrimitiveSchemaMcpElicitationLegacyTitledEnumSchemaJsonConverter : JsonConverter<McpElicitationPrimitiveSchemaMcpElicitationLegacyTitledEnumSchema>
{
    public override McpElicitationPrimitiveSchemaMcpElicitationLegacyTitledEnumSchema Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<McpElicitationPrimitiveSchema>(ref reader, options) as McpElicitationPrimitiveSchemaMcpElicitationLegacyTitledEnumSchema ?? throw new JsonException("Expected McpElicitationPrimitiveSchemaMcpElicitationLegacyTitledEnumSchema.");
    public override void Write(Utf8JsonWriter writer, McpElicitationPrimitiveSchemaMcpElicitationLegacyTitledEnumSchema concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
