// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpElicitationPrimitiveSchemaMcpElicitationNumberSchemaJsonConverter))]
public class McpElicitationPrimitiveSchemaMcpElicitationNumberSchema : McpElicitationPrimitiveSchema
{
    public McpElicitationNumberSchema Value { get; set; } = default!;
}
