// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpServerStartupStateJsonConverter : JsonConverter<McpServerStartupState>
{
    private static McpServerStartupState Parse(string? value) => value switch
    {
        "cancelled" => McpServerStartupState.Cancelled,
        "failed" => McpServerStartupState.Failed,
        "ready" => McpServerStartupState.Ready,
        "starting" => McpServerStartupState.Starting,
        _ => throw new JsonException("Unknown McpServerStartupState value: " + value)
    };
    private static string Format(McpServerStartupState value) => value switch
    {
        McpServerStartupState.Cancelled => "cancelled",
        McpServerStartupState.Failed => "failed",
        McpServerStartupState.Ready => "ready",
        McpServerStartupState.Starting => "starting",
        _ => throw new JsonException("Unknown McpServerStartupState value: " + value)
    };
    public override McpServerStartupState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for McpServerStartupState.");
    public override void Write(Utf8JsonWriter writer, McpServerStartupState value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override McpServerStartupState ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, McpServerStartupState value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
