// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpServerElicitationActionJsonConverter : JsonConverter<McpServerElicitationAction>
{
    private static McpServerElicitationAction Parse(string? value) => value switch
    {
        "accept" => McpServerElicitationAction.Accept,
        "cancel" => McpServerElicitationAction.Cancel,
        "decline" => McpServerElicitationAction.Decline,
        _ => throw new JsonException("Unknown McpServerElicitationAction value: " + value)
    };
    private static string Format(McpServerElicitationAction value) => value switch
    {
        McpServerElicitationAction.Accept => "accept",
        McpServerElicitationAction.Cancel => "cancel",
        McpServerElicitationAction.Decline => "decline",
        _ => throw new JsonException("Unknown McpServerElicitationAction value: " + value)
    };
    public override McpServerElicitationAction Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for McpServerElicitationAction.");
    public override void Write(Utf8JsonWriter writer, McpServerElicitationAction value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override McpServerElicitationAction ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, McpServerElicitationAction value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
