// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(McpServerElicitationRequestParamsJsonConverter))]
public abstract class McpServerElicitationRequestParams
{
    private protected McpServerElicitationRequestParams() { }
}
