// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpServerElicitationRequestResponse
{
    /// <summary>
    ///     Optional client metadata for form-mode action handling.
    /// </summary>
    [JsonPropertyName("_meta")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<JsonElement> Meta { get; set; }

    [JsonPropertyName("action")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public McpServerElicitationAction Action { get; set; } = default!;

    /// <summary>
    ///     Structured user input for accepted elicitations, mirroring RMCP `CreateElicitationResult`.
    ///     
    ///     This is nullable because decline/cancel responses have no content.
    /// </summary>
    [JsonPropertyName("content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<JsonElement> Content { get; set; }

}
