// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpToolCallStatusJsonConverter : JsonConverter<McpToolCallStatus>
{
    private static McpToolCallStatus Parse(string? value) => value switch
    {
        "completed" => McpToolCallStatus.Completed,
        "failed" => McpToolCallStatus.Failed,
        "inProgress" => McpToolCallStatus.InProgress,
        _ => throw new JsonException("Unknown McpToolCallStatus value: " + value)
    };
    private static string Format(McpToolCallStatus value) => value switch
    {
        McpToolCallStatus.Completed => "completed",
        McpToolCallStatus.Failed => "failed",
        McpToolCallStatus.InProgress => "inProgress",
        _ => throw new JsonException("Unknown McpToolCallStatus value: " + value)
    };
    public override McpToolCallStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for McpToolCallStatus.");
    public override void Write(Utf8JsonWriter writer, McpToolCallStatus value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override McpToolCallStatus ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, McpToolCallStatus value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
