// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpToolCallThreadItem : ThreadItem
{
    [JsonPropertyName("appContext")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<McpToolCallAppContext?> AppContext { get; set; }

    [JsonPropertyName("arguments")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public JsonElement Arguments { get; set; } = default!;

    /// <summary>
    ///     The duration of the MCP tool call in milliseconds.
    /// </summary>
    [JsonPropertyName("durationMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> DurationMs { get; set; }

    [JsonPropertyName("error")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<McpToolCallError?> Error { get; set; }

    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    /// <summary>
    ///     Deprecated: use `appContext.resourceUri` instead.
    /// </summary>
    [JsonPropertyName("mcpAppResourceUri")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> McpAppResourceUri { get; set; }

    [JsonPropertyName("pluginId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> PluginId { get; set; }

    [JsonPropertyName("readOnlyHint")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> ReadOnlyHint { get; set; }

    [JsonPropertyName("result")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<McpToolCallResult?> Result { get; set; }

    [JsonPropertyName("server")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Server { get; set; } = default!;

    [JsonPropertyName("status")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public McpToolCallStatus Status { get; set; } = default!;

    [JsonPropertyName("tool")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Tool { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "mcpToolCall";
        private set
        {
            if (value != "mcpToolCall")
            {
                throw new JsonException("Expected McpToolCallThreadItem.type to be mcpToolCall.");
            }
        }
    }

}
