// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpToolCallAppContext
{
    [JsonPropertyName("actionName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ActionName { get; set; }

    [JsonPropertyName("appName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> AppName { get; set; }

    [JsonPropertyName("connectorId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ConnectorId { get; set; } = default!;

    [JsonPropertyName("linkId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> LinkId { get; set; }

    [JsonPropertyName("resourceUri")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ResourceUri { get; set; }

}
