// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class McpToolCallGuardianApprovalReviewAction : GuardianApprovalReviewAction
{
    [JsonPropertyName("connectorId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ConnectorId { get; set; }

    [JsonPropertyName("connectorName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ConnectorName { get; set; }

    [JsonPropertyName("server")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Server { get; set; } = default!;

    [JsonPropertyName("toolName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ToolName { get; set; } = default!;

    [JsonPropertyName("toolTitle")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ToolTitle { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "mcpToolCall";
        private set
        {
            if (value != "mcpToolCall")
            {
                throw new JsonException("Expected McpToolCallGuardianApprovalReviewAction.type to be mcpToolCall.");
            }
        }
    }

}
