// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ModelProviderCapabilitiesReadRequest : ClientRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "modelProvider/capabilities/read";
        private set
        {
            if (value != "modelProvider/capabilities/read")
            {
                throw new JsonException("Expected ModelProviderCapabilitiesReadRequest.method to be modelProvider/capabilities/read.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ModelProviderCapabilitiesReadParams Params { get; set; } = default!;

}
