// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class Model
{
    /// <summary>
    ///     Deprecated: use `serviceTiers` instead.
    /// </summary>
    [JsonPropertyName("additionalSpeedTiers")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>> AdditionalSpeedTiers { get; set; }

    [JsonPropertyName("availabilityNux")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ModelAvailabilityNux?> AvailabilityNux { get; set; }

    [JsonPropertyName("defaultReasoningEffort")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string DefaultReasoningEffort { get; set; } = default!;

    /// <summary>
    ///     Catalog default service tier id for this model, when one is configured.
    /// </summary>
    [JsonPropertyName("defaultServiceTier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> DefaultServiceTier { get; set; }

    [JsonPropertyName("description")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Description { get; set; } = default!;

    [JsonPropertyName("displayName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string DisplayName { get; set; } = default!;

    [JsonPropertyName("hidden")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool Hidden { get; set; } = default!;

    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    [JsonPropertyName("inputModalities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<InputModality>> InputModalities { get; set; }

    [JsonPropertyName("isDefault")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool IsDefault { get; set; } = default!;

    [JsonPropertyName("model")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Model2 { get; set; } = default!;

    [JsonPropertyName("modelSpecialty")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ModelSpecialty { get; set; }

    /// <summary>
    ///     Multi-agent runtime declared by this model, when available.
    /// </summary>
    [JsonPropertyName("multiAgentVersion")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<MultiAgentVersion?> MultiAgentVersion { get; set; }

    [JsonPropertyName("serviceTiers")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<ModelServiceTier>> ServiceTiers { get; set; }

    [JsonPropertyName("supportedReasoningEfforts")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ReasoningEffortOption> SupportedReasoningEfforts { get; set; } = default!;

    [JsonPropertyName("supportsPersonality")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> SupportsPersonality { get; set; }

    [JsonPropertyName("upgrade")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Upgrade { get; set; }

    [JsonPropertyName("upgradeInfo")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ModelUpgradeInfo?> UpgradeInfo { get; set; }

}
