// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class MultiAgentVersionJsonConverter : JsonConverter<MultiAgentVersion>
{
    private static MultiAgentVersion Parse(string? value) => value switch
    {
        "disabled" => MultiAgentVersion.Disabled,
        "v1" => MultiAgentVersion.V1,
        "v2" => MultiAgentVersion.V2,
        _ => throw new JsonException("Unknown MultiAgentVersion value: " + value)
    };
    private static string Format(MultiAgentVersion value) => value switch
    {
        MultiAgentVersion.Disabled => "disabled",
        MultiAgentVersion.V1 => "v1",
        MultiAgentVersion.V2 => "v2",
        _ => throw new JsonException("Unknown MultiAgentVersion value: " + value)
    };
    public override MultiAgentVersion Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for MultiAgentVersion.");
    public override void Write(Utf8JsonWriter writer, MultiAgentVersion value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override MultiAgentVersion ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, MultiAgentVersion value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
