// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(NetworkPolicyRuleActionJsonConverter))]
public enum NetworkPolicyRuleAction
{
    Allow,
    Deny,
}
