// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class NetworkApprovalProtocolJsonConverter : JsonConverter<NetworkApprovalProtocol>
{
    private static NetworkApprovalProtocol Parse(string? value) => value switch
    {
        "http" => NetworkApprovalProtocol.Http,
        "https" => NetworkApprovalProtocol.Https,
        "socks5Tcp" => NetworkApprovalProtocol.Socks5Tcp,
        "socks5Udp" => NetworkApprovalProtocol.Socks5Udp,
        _ => throw new JsonException("Unknown NetworkApprovalProtocol value: " + value)
    };
    private static string Format(NetworkApprovalProtocol value) => value switch
    {
        NetworkApprovalProtocol.Http => "http",
        NetworkApprovalProtocol.Https => "https",
        NetworkApprovalProtocol.Socks5Tcp => "socks5Tcp",
        NetworkApprovalProtocol.Socks5Udp => "socks5Udp",
        _ => throw new JsonException("Unknown NetworkApprovalProtocol value: " + value)
    };
    public override NetworkApprovalProtocol Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for NetworkApprovalProtocol.");
    public override void Write(Utf8JsonWriter writer, NetworkApprovalProtocol value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override NetworkApprovalProtocol ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, NetworkApprovalProtocol value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
