// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class NetworkPolicyRuleActionJsonConverter : JsonConverter<NetworkPolicyRuleAction>
{
    private static NetworkPolicyRuleAction Parse(string? value) => value switch
    {
        "allow" => NetworkPolicyRuleAction.Allow,
        "deny" => NetworkPolicyRuleAction.Deny,
        _ => throw new JsonException("Unknown NetworkPolicyRuleAction value: " + value)
    };
    private static string Format(NetworkPolicyRuleAction value) => value switch
    {
        NetworkPolicyRuleAction.Allow => "allow",
        NetworkPolicyRuleAction.Deny => "deny",
        _ => throw new JsonException("Unknown NetworkPolicyRuleAction value: " + value)
    };
    public override NetworkPolicyRuleAction Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for NetworkPolicyRuleAction.");
    public override void Write(Utf8JsonWriter writer, NetworkPolicyRuleAction value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override NetworkPolicyRuleAction ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, NetworkPolicyRuleAction value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
