// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class NetworkRequirements
{
    [JsonPropertyName("allowLocalBinding")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> AllowLocalBinding { get; set; }

    /// <summary>
    ///     Legacy compatibility view derived from `unix_sockets`.
    /// </summary>
    [JsonPropertyName("allowUnixSockets")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>?> AllowUnixSockets { get; set; }

    [JsonPropertyName("allowUpstreamProxy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> AllowUpstreamProxy { get; set; }

    /// <summary>
    ///     Legacy compatibility view derived from `domains`.
    /// </summary>
    [JsonPropertyName("allowedDomains")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>?> AllowedDomains { get; set; }

    [JsonPropertyName("dangerouslyAllowAllUnixSockets")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> DangerouslyAllowAllUnixSockets { get; set; }

    [JsonPropertyName("dangerouslyAllowNonLoopbackProxy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> DangerouslyAllowNonLoopbackProxy { get; set; }

    /// <summary>
    ///     Legacy compatibility view derived from `domains`.
    /// </summary>
    [JsonPropertyName("deniedDomains")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>?> DeniedDomains { get; set; }

    /// <summary>
    ///     Canonical network permission map for `experimental_network`.
    /// </summary>
    [JsonPropertyName("domains")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Dictionary<string, NetworkDomainPermission>?> Domains { get; set; }

    [JsonPropertyName("enabled")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> Enabled { get; set; }

    [JsonPropertyName("httpPort")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ushort?> HttpPort { get; set; }

    /// <summary>
    ///     When true, only managed allowlist entries are respected while managed network enforcement is active.
    /// </summary>
    [JsonPropertyName("managedAllowedDomainsOnly")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> ManagedAllowedDomainsOnly { get; set; }

    [JsonPropertyName("socksPort")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ushort?> SocksPort { get; set; }

    /// <summary>
    ///     Canonical unix socket permission map for `experimental_network`.
    /// </summary>
    [JsonPropertyName("unixSockets")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Dictionary<string, NetworkUnixSocketPermission>?> UnixSockets { get; set; }

}
