// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class NetworkPolicyAmendment
{
    [JsonPropertyName("action")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public NetworkPolicyRuleAction Action { get; set; } = default!;

    [JsonPropertyName("host")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Host { get; set; } = default!;

}
