// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class NetworkDomainPermissionJsonConverter : JsonConverter<NetworkDomainPermission>
{
    private static NetworkDomainPermission Parse(string? value) => value switch
    {
        "allow" => NetworkDomainPermission.Allow,
        "deny" => NetworkDomainPermission.Deny,
        _ => throw new JsonException("Unknown NetworkDomainPermission value: " + value)
    };
    private static string Format(NetworkDomainPermission value) => value switch
    {
        NetworkDomainPermission.Allow => "allow",
        NetworkDomainPermission.Deny => "deny",
        _ => throw new JsonException("Unknown NetworkDomainPermission value: " + value)
    };
    public override NetworkDomainPermission Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for NetworkDomainPermission.");
    public override void Write(Utf8JsonWriter writer, NetworkDomainPermission value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override NetworkDomainPermission ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, NetworkDomainPermission value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
