// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class OtherResponseItem : ResponseItem
{
    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "other";
        private set
        {
            if (value != "other")
            {
                throw new JsonException("Expected OtherResponseItem.type to be other.");
            }
        }
    }

}
