// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class OutputTextContentItem : ContentItem
{
    [JsonPropertyName("text")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Text { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "output_text";
        private set
        {
            if (value != "output_text")
            {
                throw new JsonException("Expected OutputTextContentItem.type to be output_text.");
            }
        }
    }

}
