// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ParsedCommandJsonConverter))]
public abstract class ParsedCommand
{
    private protected ParsedCommand() { }
}
