// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PermissionGrantScopeJsonConverter : JsonConverter<PermissionGrantScope>
{
    private static PermissionGrantScope Parse(string? value) => value switch
    {
        "session" => PermissionGrantScope.Session,
        "turn" => PermissionGrantScope.Turn,
        _ => throw new JsonException("Unknown PermissionGrantScope value: " + value)
    };
    private static string Format(PermissionGrantScope value) => value switch
    {
        PermissionGrantScope.Session => "session",
        PermissionGrantScope.Turn => "turn",
        _ => throw new JsonException("Unknown PermissionGrantScope value: " + value)
    };
    public override PermissionGrantScope Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for PermissionGrantScope.");
    public override void Write(Utf8JsonWriter writer, PermissionGrantScope value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override PermissionGrantScope ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, PermissionGrantScope value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
