// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PermissionsRequestApprovalResponse
{
    [JsonPropertyName("permissions")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public GrantedPermissionProfile Permissions { get; set; } = default!;

    [JsonPropertyName("scope")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<PermissionGrantScope> Scope { get; set; }

    /// <summary>
    ///     Review every subsequent command in this turn before normal sandboxed execution.
    /// </summary>
    [JsonPropertyName("strictAutoReview")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> StrictAutoReview { get; set; }

}
