// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginShareDeleteParams
{
    [JsonPropertyName("remotePluginId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string RemotePluginId { get; set; } = default!;

}
