// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginShareTarget
{
    [JsonPropertyName("principalId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string PrincipalId { get; set; } = default!;

    [JsonPropertyName("principalType")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PluginSharePrincipalType PrincipalType { get; set; } = default!;

    [JsonPropertyName("role")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PluginShareTargetRole Role { get; set; } = default!;

}
