// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(PluginShareUpdateDiscoverabilityJsonConverter))]
public enum PluginShareUpdateDiscoverability
{
    LISTED,
    PRIVATE,
    UNLISTED,
}
