// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Bundle and installed-state changes observed by this pass, not a runtime-readiness acknowledgement or a cumulative diff since the client's last request. Other metadata-only changes are not listed.
/// </summary>
public class PluginReconcileResponse
{
    /// <summary>
    ///     Plugins affected by bundle changes, enablement changes, or removals. Installed-state changes compare against the previous cached snapshot, including cached reinstalls. Removal hints survive cache cleanup failures; unchanged plugins are omitted.
    /// </summary>
    [JsonPropertyName("changedPlugins")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<PluginReconcileChangedPlugin> ChangedPlugins { get; set; } = default!;

    /// <summary>
    ///     Subset of failures for which the requested bundle could not be materialized. A previously cached version may still be available.
    /// </summary>
    [JsonPropertyName("failedMaterializationRemotePluginIds")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> FailedMaterializationRemotePluginIds { get; set; } = default!;

    /// <summary>
    ///     Backend remote plugin IDs whose bundle or identity update failed.
    /// </summary>
    [JsonPropertyName("failedRemotePluginIds")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> FailedRemotePluginIds { get; set; } = default!;

}
