// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginDetail
{
    [JsonPropertyName("appTemplates")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<AppTemplateSummary> AppTemplates { get; set; } = default!;

    [JsonPropertyName("apps")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<AppSummary> Apps { get; set; } = default!;

    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Description { get; set; }

    [JsonPropertyName("hooks")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<PluginHookSummary> Hooks { get; set; } = default!;

    [JsonPropertyName("marketplaceName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string MarketplaceName { get; set; } = default!;

    [JsonPropertyName("marketplacePath")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> MarketplacePath { get; set; }

    [JsonPropertyName("mcpServers")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> McpServers { get; set; } = default!;

    [JsonPropertyName("scheduledTasks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<ScheduledTaskSummary>?> ScheduledTasks { get; set; }

    [JsonPropertyName("shareUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ShareUrl { get; set; }

    [JsonPropertyName("skills")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<SkillSummary> Skills { get; set; } = default!;

    [JsonPropertyName("summary")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PluginSummary Summary { get; set; } = default!;

}
