// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(PluginSearchScopeJsonConverter))]
public enum PluginSearchScope
{
    Global,
    Personal,
    Workspace,
}
