// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginDisabledReasonJsonConverter : JsonConverter<PluginDisabledReason>
{
    private static PluginDisabledReason Parse(string? value) => value switch
    {
        "disabled_by_admin" => PluginDisabledReason.DisabledByAdmin,
        "plan_not_eligible" => PluginDisabledReason.PlanNotEligible,
        "required_app_unavailable" => PluginDisabledReason.RequiredAppUnavailable,
        "unknown" => PluginDisabledReason.Unknown,
        _ => throw new JsonException("Unknown PluginDisabledReason value: " + value)
    };
    private static string Format(PluginDisabledReason value) => value switch
    {
        PluginDisabledReason.DisabledByAdmin => "disabled_by_admin",
        PluginDisabledReason.PlanNotEligible => "plan_not_eligible",
        PluginDisabledReason.RequiredAppUnavailable => "required_app_unavailable",
        PluginDisabledReason.Unknown => "unknown",
        _ => throw new JsonException("Unknown PluginDisabledReason value: " + value)
    };
    public override PluginDisabledReason Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for PluginDisabledReason.");
    public override void Write(Utf8JsonWriter writer, PluginDisabledReason value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override PluginDisabledReason ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, PluginDisabledReason value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
