// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginListResponse
{
    [JsonPropertyName("featuredPluginIds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>> FeaturedPluginIds { get; set; }

    [JsonPropertyName("marketplaceLoadErrors")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<MarketplaceLoadErrorInfo>> MarketplaceLoadErrors { get; set; }

    [JsonPropertyName("marketplaces")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<PluginMarketplaceEntry> Marketplaces { get; set; } = default!;

}
