// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginInstallResponse
{
    [JsonPropertyName("appsNeedingAuth")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<AppSummary> AppsNeedingAuth { get; set; } = default!;

    [JsonPropertyName("authPolicy")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PluginAuthPolicy AuthPolicy { get; set; } = default!;

}
