// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginSharePrincipalRoleJsonConverter : JsonConverter<PluginSharePrincipalRole>
{
    private static PluginSharePrincipalRole Parse(string? value) => value switch
    {
        "editor" => PluginSharePrincipalRole.Editor,
        "owner" => PluginSharePrincipalRole.Owner,
        "reader" => PluginSharePrincipalRole.Reader,
        _ => throw new JsonException("Unknown PluginSharePrincipalRole value: " + value)
    };
    private static string Format(PluginSharePrincipalRole value) => value switch
    {
        PluginSharePrincipalRole.Editor => "editor",
        PluginSharePrincipalRole.Owner => "owner",
        PluginSharePrincipalRole.Reader => "reader",
        _ => throw new JsonException("Unknown PluginSharePrincipalRole value: " + value)
    };
    public override PluginSharePrincipalRole Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for PluginSharePrincipalRole.");
    public override void Write(Utf8JsonWriter writer, PluginSharePrincipalRole value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override PluginSharePrincipalRole ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, PluginSharePrincipalRole value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
