// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginSearchResult
{
    [JsonPropertyName("marketplaceName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string MarketplaceName { get; set; } = default!;

    [JsonPropertyName("marketplacePath")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> MarketplacePath { get; set; }

    [JsonPropertyName("plugin")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PluginSummary Plugin { get; set; } = default!;

}
