// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginShareUpdateTargetsResponse
{
    [JsonPropertyName("discoverability")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public PluginShareDiscoverability Discoverability { get; set; } = default!;

    [JsonPropertyName("principals")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<PluginSharePrincipal> Principals { get; set; } = default!;

}
