// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginInstalledParams
{
    /// <summary>
    ///     Optional working directories used to discover repo marketplaces.
    /// </summary>
    [JsonPropertyName("cwds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>?> Cwds { get; set; }

    /// <summary>
    ///     Additional uninstalled plugin names that should be returned when present locally. This is used by mention surfaces that intentionally expose install entrypoints.
    /// </summary>
    [JsonPropertyName("installSuggestionPluginNames")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>?> InstallSuggestionPluginNames { get; set; }

}
