// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PluginReadParams
{
    [JsonPropertyName("marketplacePath")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> MarketplacePath { get; set; }

    [JsonPropertyName("pluginName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string PluginName { get; set; } = default!;

    [JsonPropertyName("remoteMarketplaceName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> RemoteMarketplaceName { get; set; }

}
