// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ProcessOutputStreamJsonConverter : JsonConverter<ProcessOutputStream>
{
    private static ProcessOutputStream Parse(string? value) => value switch
    {
        "stderr" => ProcessOutputStream.Stderr,
        "stdout" => ProcessOutputStream.Stdout,
        _ => throw new JsonException("Unknown ProcessOutputStream value: " + value)
    };
    private static string Format(ProcessOutputStream value) => value switch
    {
        ProcessOutputStream.Stderr => "stderr",
        ProcessOutputStream.Stdout => "stdout",
        _ => throw new JsonException("Unknown ProcessOutputStream value: " + value)
    };
    public override ProcessOutputStream Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for ProcessOutputStream.");
    public override void Write(Utf8JsonWriter writer, ProcessOutputStream value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override ProcessOutputStream ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, ProcessOutputStream value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
