// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Stream label for `process/outputDelta` notifications.
/// </summary>
[JsonConverter(typeof(ProcessOutputStreamJsonConverter))]
public enum ProcessOutputStream
{
    Stderr,
    Stdout,
}
