// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Final exit notification for a `process/spawn` session.
/// </summary>
public class ProcessExitedNotification2 : ServerNotification
{
    /// <summary>
    ///     Unix timestamp (in milliseconds) when app-server emitted this notification.
    /// </summary>
    [JsonPropertyName("emittedAtMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long> EmittedAtMs { get; set; }

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "process/exited";
        private set
        {
            if (value != "process/exited")
            {
                throw new JsonException("Expected ProcessExitedNotification2.method to be process/exited.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ProcessExitedNotification Params { get; set; } = default!;

}
