// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ProjectChangeTypeJsonConverter))]
public enum ProjectChangeType
{
    Created,
    Deleted,
    Updated,
}
