// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class Project
{
    [JsonPropertyName("createdAt")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public long CreatedAt { get; set; } = default!;

    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    [JsonPropertyName("metadata")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public Dictionary<string, string> Metadata { get; set; } = default!;

    [JsonPropertyName("name")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Name { get; set; } = default!;

    [JsonPropertyName("position")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public long Position { get; set; } = default!;

    /// <summary>
    ///     Newest non-archived member thread's recency, in Unix seconds; null when none exist.
    /// </summary>
    [JsonPropertyName("recencyAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> RecencyAt { get; set; }

    [JsonPropertyName("roots")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ProjectRoot> Roots { get; set; } = default!;

    [JsonPropertyName("updatedAt")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public long UpdatedAt { get; set; } = default!;

}
