// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ProjectChangeTypeJsonConverter : JsonConverter<ProjectChangeType>
{
    private static ProjectChangeType Parse(string? value) => value switch
    {
        "created" => ProjectChangeType.Created,
        "deleted" => ProjectChangeType.Deleted,
        "updated" => ProjectChangeType.Updated,
        _ => throw new JsonException("Unknown ProjectChangeType value: " + value)
    };
    private static string Format(ProjectChangeType value) => value switch
    {
        ProjectChangeType.Created => "created",
        ProjectChangeType.Deleted => "deleted",
        ProjectChangeType.Updated => "updated",
        _ => throw new JsonException("Unknown ProjectChangeType value: " + value)
    };
    public override ProjectChangeType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for ProjectChangeType.");
    public override void Write(Utf8JsonWriter writer, ProjectChangeType value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override ProjectChangeType ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, ProjectChangeType value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
