// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class PromptConfiguredHookHandler : ConfiguredHookHandler
{
    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "prompt";
        private set
        {
            if (value != "prompt")
            {
                throw new JsonException("Expected PromptConfiguredHookHandler.type to be prompt.");
            }
        }
    }

}
