// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class RateLimitResetTypeJsonConverter : JsonConverter<RateLimitResetType>
{
    private static RateLimitResetType Parse(string? value) => value switch
    {
        "codexRateLimits" => RateLimitResetType.CodexRateLimits,
        "unknown" => RateLimitResetType.Unknown,
        _ => throw new JsonException("Unknown RateLimitResetType value: " + value)
    };
    private static string Format(RateLimitResetType value) => value switch
    {
        RateLimitResetType.CodexRateLimits => "codexRateLimits",
        RateLimitResetType.Unknown => "unknown",
        _ => throw new JsonException("Unknown RateLimitResetType value: " + value)
    };
    public override RateLimitResetType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for RateLimitResetType.");
    public override void Write(Utf8JsonWriter writer, RateLimitResetType value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override RateLimitResetType ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, RateLimitResetType value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
