// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ReadOnlySandboxPolicy : SandboxPolicy
{
    [JsonPropertyName("networkAccess")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> NetworkAccess { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "readOnly";
        private set
        {
            if (value != "readOnly")
            {
                throw new JsonException("Expected ReadOnlySandboxPolicy.type to be readOnly.");
            }
        }
    }

}
