// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class RealtimeThreadTimelineEntry : ThreadTimelineEntry
{
    [JsonPropertyName("item")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadRealtimeItem Item { get; set; } = default!;

    [JsonPropertyName("position")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ulong Position { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "realtime";
        private set
        {
            if (value != "realtime")
            {
                throw new JsonException("Expected RealtimeThreadTimelineEntry.type to be realtime.");
            }
        }
    }

}
