// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(RealtimeOutputModalityJsonConverter))]
public enum RealtimeOutputModality
{
    Audio,
    Text,
}
