// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(RemoteControlConnectionStatusJsonConverter))]
public enum RemoteControlConnectionStatus
{
    Connected,
    Connecting,
    Disabled,
    Errored,
}
