// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class RemoteControlConnectionStatusJsonConverter : JsonConverter<RemoteControlConnectionStatus>
{
    private static RemoteControlConnectionStatus Parse(string? value) => value switch
    {
        "connected" => RemoteControlConnectionStatus.Connected,
        "connecting" => RemoteControlConnectionStatus.Connecting,
        "disabled" => RemoteControlConnectionStatus.Disabled,
        "errored" => RemoteControlConnectionStatus.Errored,
        _ => throw new JsonException("Unknown RemoteControlConnectionStatus value: " + value)
    };
    private static string Format(RemoteControlConnectionStatus value) => value switch
    {
        RemoteControlConnectionStatus.Connected => "connected",
        RemoteControlConnectionStatus.Connecting => "connecting",
        RemoteControlConnectionStatus.Disabled => "disabled",
        RemoteControlConnectionStatus.Errored => "errored",
        _ => throw new JsonException("Unknown RemoteControlConnectionStatus value: " + value)
    };
    public override RemoteControlConnectionStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for RemoteControlConnectionStatus.");
    public override void Write(Utf8JsonWriter writer, RemoteControlConnectionStatus value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override RemoteControlConnectionStatus ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, RemoteControlConnectionStatus value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
