// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     The plugin is available in the remote catalog. Download metadata is kept server-side and is not exposed through the app-server API.
/// </summary>
public class RemotePluginSource : PluginSource
{
    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "remote";
        private set
        {
            if (value != "remote")
            {
                throw new JsonException("Expected RemotePluginSource.type to be remote.");
            }
        }
    }

}
