// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Current remote-control connection status and remote identity exposed to clients.
/// </summary>
public class RemoteControlStatusChangedNotification
{
    [JsonPropertyName("environmentId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> EnvironmentId { get; set; }

    [JsonPropertyName("installationId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string InstallationId { get; set; } = default!;

    [JsonPropertyName("serverName")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ServerName { get; set; } = default!;

    [JsonPropertyName("status")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RemoteControlConnectionStatus Status { get; set; } = default!;

}
