// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class RequestIdIntegerJsonConverter : JsonConverter<RequestIdInteger>
{
    public override RequestIdInteger Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<RequestId>(ref reader, options) as RequestIdInteger ?? throw new JsonException("Expected RequestIdInteger.");
    public override void Write(Utf8JsonWriter writer, RequestIdInteger concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
