// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class RequestIdStringJsonConverter : JsonConverter<RequestIdString>
{
    public override RequestIdString Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<RequestId>(ref reader, options) as RequestIdString ?? throw new JsonException("Expected RequestIdString.");
    public override void Write(Utf8JsonWriter writer, RequestIdString concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
