// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(RequestIdIntegerJsonConverter))]
public class RequestIdInteger : RequestId
{
    public RequestIdInteger(long value)
    {
        Value = value;
    }

    public long Value { get; }
}
