// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ResourceContentBlobJsonConverter : JsonConverter<ResourceContentBlob>
{
    public override ResourceContentBlob Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<ResourceContent>(ref reader, options) as ResourceContentBlob ?? throw new JsonException("Expected ResourceContentBlob.");
    public override void Write(Utf8JsonWriter writer, ResourceContentBlob concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
