// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ResourceContentJsonConverter : JsonConverter<ResourceContent>
{
    public override ResourceContent Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind == JsonValueKind.Object && root.TryGetProperty("blob", out var property0))
            return new ResourceContentBlob { Value = root.Deserialize<ResourceContent2>(options)! };
        if (root.ValueKind == JsonValueKind.Object && root.TryGetProperty("text", out var property1))
            return new ResourceContentText { Value = root.Deserialize<ResourceContent3>(options)! };
        throw new JsonException("Unknown ResourceContent wire shape or value.");
    }

    public override void Write(Utf8JsonWriter writer, ResourceContent value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case ResourceContentBlob concrete:
                JsonSerializer.Serialize(writer, concrete.Value, options);
                break;
            case ResourceContentText concrete:
                JsonSerializer.Serialize(writer, concrete.Value, options);
                break;
            default: throw new JsonException("Unknown runtime type for ResourceContent.");
        }
    }
}
