// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ResourceContentTextJsonConverter))]
public class ResourceContentText : ResourceContent
{
    public ResourceContent3 Value { get; set; } = default!;
}
