// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ResponsesApiWebSearchActionJsonConverter : JsonConverter<ResponsesApiWebSearchAction>
{
    public override ResponsesApiWebSearchAction Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ResponsesApiWebSearchAction type.");
        return discriminator.GetString() switch
        {
            "find_in_page" => root.Deserialize<FindInPageResponsesApiWebSearchAction>(options) ?? throw new JsonException("Expected FindInPageResponsesApiWebSearchAction."),
            "open_page" => root.Deserialize<OpenPageResponsesApiWebSearchAction>(options) ?? throw new JsonException("Expected OpenPageResponsesApiWebSearchAction."),
            "other" => root.Deserialize<OtherResponsesApiWebSearchAction>(options) ?? throw new JsonException("Expected OtherResponsesApiWebSearchAction."),
            "search" => root.Deserialize<SearchResponsesApiWebSearchAction>(options) ?? throw new JsonException("Expected SearchResponsesApiWebSearchAction."),
            _ => throw new JsonException("Unknown ResponsesApiWebSearchAction type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ResponsesApiWebSearchAction value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case FindInPageResponsesApiWebSearchAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case OpenPageResponsesApiWebSearchAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case OtherResponsesApiWebSearchAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case SearchResponsesApiWebSearchAction concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ResponsesApiWebSearchAction.");
        }
    }
}
