// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Failed to connect to the response SSE stream.
/// </summary>
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public class ResponseStreamConnectionFailedCodexErrorInfo : CodexErrorInfo
{
    [JsonPropertyName("responseStreamConnectionFailed")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public CodexErrorInfoResponseStreamConnectionFailed ResponseStreamConnectionFailed { get; set; } = default!;

}
