// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ReviewDecisionTimedOutJsonConverter : JsonConverter<ReviewDecisionTimedOut>
{
    public override ReviewDecisionTimedOut Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<ReviewDecision>(ref reader, options) as ReviewDecisionTimedOut ?? throw new JsonException("Expected ReviewDecisionTimedOut.");
    public override void Write(Utf8JsonWriter writer, ReviewDecisionTimedOut concrete, JsonSerializerOptions options)
    {
        writer.WriteStringValue("timed_out");
    }
}
