// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ReviewDecisionNetworkPolicyAmendment
{
    [JsonPropertyName("network_policy_amendment")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public NetworkPolicyAmendment NetworkPolicyAmendment { get; set; } = default!;

}
