// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     User has approved this request and wants future prompts in the same session-scoped approval cache to be automatically approved for the remainder of the session.
/// </summary>
[JsonConverter(typeof(ReviewDecisionApprovedForSessionJsonConverter))]
public class ReviewDecisionApprovedForSession : ReviewDecision
{
}
