// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     User has approved this MCP tool call and wants to amend its policy so matching future calls are automatically approved across sessions.
/// </summary>
[JsonConverter(typeof(ReviewDecisionApprovedMcpPolicyAmendmentJsonConverter))]
public class ReviewDecisionApprovedMcpPolicyAmendment : ReviewDecision
{
}
