// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ReviewDecisionApprovedForSessionJsonConverter : JsonConverter<ReviewDecisionApprovedForSession>
{
    public override ReviewDecisionApprovedForSession Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<ReviewDecision>(ref reader, options) as ReviewDecisionApprovedForSession ?? throw new JsonException("Expected ReviewDecisionApprovedForSession.");
    public override void Write(Utf8JsonWriter writer, ReviewDecisionApprovedForSession concrete, JsonSerializerOptions options)
    {
        writer.WriteStringValue("approved_for_session");
    }
}
