// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Automatic approval review timed out before reaching a decision.
/// </summary>
[JsonConverter(typeof(ReviewDecisionTimedOutJsonConverter))]
public class ReviewDecisionTimedOut : ReviewDecision
{
}
