// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     User has denied this command and the agent should not do anything until the user's next command.
/// </summary>
[JsonConverter(typeof(ReviewDecisionAbortJsonConverter))]
public class ReviewDecisionAbort : ReviewDecision
{
}
