// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(SandboxPolicyJsonConverter))]
public abstract class SandboxPolicy
{
    private protected SandboxPolicy() { }
}
