// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ScheduledTaskScheduleJsonConverter : JsonConverter<ScheduledTaskSchedule>
{
    public override ScheduledTaskSchedule Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ScheduledTaskSchedule type.");
        return discriminator.GetString() switch
        {
            "daily" => root.Deserialize<DailyScheduledTaskSchedule>(options) ?? throw new JsonException("Expected DailyScheduledTaskSchedule."),
            "hourly" => root.Deserialize<HourlyScheduledTaskSchedule>(options) ?? throw new JsonException("Expected HourlyScheduledTaskSchedule."),
            "weekdays" => root.Deserialize<WeekdaysScheduledTaskSchedule>(options) ?? throw new JsonException("Expected WeekdaysScheduledTaskSchedule."),
            "weekly" => root.Deserialize<WeeklyScheduledTaskSchedule>(options) ?? throw new JsonException("Expected WeeklyScheduledTaskSchedule."),
            _ => throw new JsonException("Unknown ScheduledTaskSchedule type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ScheduledTaskSchedule value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case DailyScheduledTaskSchedule concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case HourlyScheduledTaskSchedule concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WeekdaysScheduledTaskSchedule concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WeeklyScheduledTaskSchedule concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ScheduledTaskSchedule.");
        }
    }
}
