// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SearchResponsesApiWebSearchAction : ResponsesApiWebSearchAction
{
    [JsonPropertyName("queries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>?> Queries { get; set; }

    [JsonPropertyName("query")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Query { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "search";
        private set
        {
            if (value != "search")
            {
                throw new JsonException("Expected SearchResponsesApiWebSearchAction.type to be search.");
            }
        }
    }

}
