// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SendAddCreditsNudgeEmailParams
{
    [JsonPropertyName("creditType")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public AddCreditsNudgeCreditType CreditType { get; set; } = default!;

}
