// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Request initiated from the server and sent to the client.
/// </summary>
[JsonConverter(typeof(ServerRequestJsonConverter))]
public abstract class ServerRequest
{
    private protected ServerRequest() { }
}
