// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ServerDiagnosticsProcess
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public uint Id { get; set; } = default!;

    [JsonPropertyName("physicalFootprintBytes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ulong?> PhysicalFootprintBytes { get; set; }

    [JsonPropertyName("residentMemoryBytes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ulong?> ResidentMemoryBytes { get; set; }

}
