// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ServerRequestResolvedNotification2 : ServerNotification
{
    /// <summary>
    ///     Unix timestamp (in milliseconds) when app-server emitted this notification.
    /// </summary>
    [JsonPropertyName("emittedAtMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long> EmittedAtMs { get; set; }

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "serverRequest/resolved";
        private set
        {
            if (value != "serverRequest/resolved")
            {
                throw new JsonException("Expected ServerRequestResolvedNotification2.method to be serverRequest/resolved.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ServerRequestResolvedNotification Params { get; set; } = default!;

}
