// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Session-layer overrides supplied via `-c`/`--config`.
/// </summary>
public class SessionFlagsConfigLayerSource : ConfigLayerSource
{
    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "sessionFlags";
        private set
        {
            if (value != "sessionFlags")
            {
                throw new JsonException("Expected SessionFlagsConfigLayerSource.type to be sessionFlags.");
            }
        }
    }

}
