// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SessionSourceExecJsonConverter : JsonConverter<SessionSourceExec>
{
    public override SessionSourceExec Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<SessionSource>(ref reader, options) as SessionSourceExec ?? throw new JsonException("Expected SessionSourceExec.");
    public override void Write(Utf8JsonWriter writer, SessionSourceExec concrete, JsonSerializerOptions options)
    {
        writer.WriteStringValue("exec");
    }
}
