// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SkillsListParams
{
    /// <summary>
    ///     When empty, defaults to the current session working directory.
    /// </summary>
    [JsonPropertyName("cwds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>> Cwds { get; set; }

    /// <summary>
    ///     When true, bypass the skills cache and re-scan skills from disk.
    /// </summary>
    [JsonPropertyName("forceReload")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> ForceReload { get; set; }

}
