// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SkillInterface
{
    [JsonPropertyName("brandColor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> BrandColor { get; set; }

    [JsonPropertyName("defaultPrompt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> DefaultPrompt { get; set; }

    [JsonPropertyName("displayName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> DisplayName { get; set; }

    [JsonPropertyName("iconLarge")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> IconLarge { get; set; }

    /// <summary>
    ///     Remote large icon URL from the plugin catalog.
    /// </summary>
    [JsonPropertyName("iconLargeUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> IconLargeUrl { get; set; }

    [JsonPropertyName("iconSmall")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> IconSmall { get; set; }

    /// <summary>
    ///     Remote small icon URL from the plugin catalog.
    /// </summary>
    [JsonPropertyName("iconSmallUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> IconSmallUrl { get; set; }

    [JsonPropertyName("shortDescription")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ShortDescription { get; set; }

}
