// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SkillMetadata
{
    [JsonPropertyName("dependencies")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SkillDependencies?> Dependencies { get; set; }

    [JsonPropertyName("description")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Description { get; set; } = default!;

    [JsonPropertyName("enabled")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public bool Enabled { get; set; } = default!;

    [JsonPropertyName("interface")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SkillInterface?> Interface { get; set; }

    [JsonPropertyName("name")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Name { get; set; } = default!;

    [JsonPropertyName("path")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Path { get; set; } = default!;

    /// <summary>
    ///     Owning plugin ID, matching `PluginSummary.id`, when known.
    /// </summary>
    [JsonPropertyName("pluginId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> PluginId { get; set; }

    [JsonPropertyName("scope")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public SkillScope Scope { get; set; } = default!;

    /// <summary>
    ///     Legacy short_description from SKILL.md. Prefer SKILL.json interface.short_description.
    /// </summary>
    [JsonPropertyName("shortDescription")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ShortDescription { get; set; }

}
