// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SkillScopeJsonConverter : JsonConverter<SkillScope>
{
    private static SkillScope Parse(string? value) => value switch
    {
        "admin" => SkillScope.Admin,
        "repo" => SkillScope.Repo,
        "system" => SkillScope.System,
        "user" => SkillScope.User,
        _ => throw new JsonException("Unknown SkillScope value: " + value)
    };
    private static string Format(SkillScope value) => value switch
    {
        SkillScope.Admin => "admin",
        SkillScope.Repo => "repo",
        SkillScope.System => "system",
        SkillScope.User => "user",
        _ => throw new JsonException("Unknown SkillScope value: " + value)
    };
    public override SkillScope Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for SkillScope.");
    public override void Write(Utf8JsonWriter writer, SkillScope value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override SkillScope ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, SkillScope value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
