// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SlashTmpFileSystemSpecialPath : FileSystemSpecialPath
{
    [JsonPropertyName("kind")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Kind
    {
        get => "slash_tmp";
        private set
        {
            if (value != "slash_tmp")
            {
                throw new JsonException("Expected SlashTmpFileSystemSpecialPath.kind to be slash_tmp.");
            }
        }
    }

}
