// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SortDirectionJsonConverter : JsonConverter<SortDirection>
{
    private static SortDirection Parse(string? value) => value switch
    {
        "asc" => SortDirection.Asc,
        "desc" => SortDirection.Desc,
        _ => throw new JsonException("Unknown SortDirection value: " + value)
    };
    private static string Format(SortDirection value) => value switch
    {
        SortDirection.Asc => "asc",
        SortDirection.Desc => "desc",
        _ => throw new JsonException("Unknown SortDirection value: " + value)
    };
    public override SortDirection Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for SortDirection.");
    public override void Write(Utf8JsonWriter writer, SortDirection value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override SortDirection ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, SortDirection value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
