// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SpecialFileSystemPath : FileSystemPath
{
    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "special";
        private set
        {
            if (value != "special")
            {
                throw new JsonException("Expected SpecialFileSystemPath.type to be special.");
            }
        }
    }

    [JsonPropertyName("value")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public FileSystemSpecialPath Value { get; set; } = default!;

}
