// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SubAgentSourceThreadSpawn
{
    [JsonPropertyName("agent_nickname")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> AgentNickname { get; set; }

    [JsonPropertyName("agent_path")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> AgentPath { get; set; }

    [JsonPropertyName("agent_role")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> AgentRole { get; set; }

    [JsonPropertyName("depth")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public int Depth { get; set; } = default!;

    [JsonPropertyName("parent_thread_id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ParentThreadId { get; set; } = default!;

}
