// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(SubAgentActivityKindJsonConverter))]
public enum SubAgentActivityKind
{
    Completed,
    Interacted,
    Interrupted,
    Started,
}
