// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class SummaryTextReasoningItemReasoningSummary : ReasoningItemReasoningSummary
{
    [JsonPropertyName("text")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Text { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "summary_text";
        private set
        {
            if (value != "summary_text")
            {
                throw new JsonException("Expected SummaryTextReasoningItemReasoningSummary.type to be summary_text.");
            }
        }
    }

}
