// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadMetadataGitInfoUpdateParams
{
    /// <summary>
    ///     Omit to leave the stored branch unchanged, set to `null` to clear it, or provide a non-empty string to replace it.
    /// </summary>
    [JsonPropertyName("branch")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Branch { get; set; }

    /// <summary>
    ///     Omit to leave the stored origin URL unchanged, set to `null` to clear it, or provide a non-empty string to replace it.
    /// </summary>
    [JsonPropertyName("originUrl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> OriginUrl { get; set; }

    /// <summary>
    ///     Omit to leave the stored commit unchanged, set to `null` to clear it, or provide a non-empty string to replace it.
    /// </summary>
    [JsonPropertyName("sha")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Sha { get; set; }

}
