// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL - one item or turn boundary in canonical rollout order.
/// </summary>
[JsonConverter(typeof(ThreadTimelineEntryJsonConverter))]
public abstract class ThreadTimelineEntry
{
    private protected ThreadTimelineEntry() { }
}
