// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL - flat transcript delta emitted whenever realtime transcript text changes.
/// </summary>
public class ThreadRealtimeTranscriptDeltaNotification
{
    /// <summary>
    ///     Live transcript delta from the realtime event.
    /// </summary>
    [JsonPropertyName("delta")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Delta { get; set; } = default!;

    [JsonPropertyName("role")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Role { get; set; } = default!;

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
