// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadRealtimeBemItemPresentationJsonConverter : JsonConverter<ThreadRealtimeBemItemPresentation>
{
    public override ThreadRealtimeBemItemPresentation Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ThreadRealtimeBemItemPresentation type.");
        return discriminator.GetString() switch
        {
            "inlineMarkdown" => root.Deserialize<InlineMarkdownThreadRealtimeBemItemPresentation>(options) ?? throw new JsonException("Expected InlineMarkdownThreadRealtimeBemItemPresentation."),
            "inlineVisualization" => root.Deserialize<InlineVisualizationThreadRealtimeBemItemPresentation>(options) ?? throw new JsonException("Expected InlineVisualizationThreadRealtimeBemItemPresentation."),
            "wholeItem" => root.Deserialize<WholeItemThreadRealtimeBemItemPresentation>(options) ?? throw new JsonException("Expected WholeItemThreadRealtimeBemItemPresentation."),
            _ => throw new JsonException("Unknown ThreadRealtimeBemItemPresentation type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ThreadRealtimeBemItemPresentation value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case InlineMarkdownThreadRealtimeBemItemPresentation concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case InlineVisualizationThreadRealtimeBemItemPresentation concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WholeItemThreadRealtimeBemItemPresentation concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ThreadRealtimeBemItemPresentation.");
        }
    }
}
