// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public class ThreadSpawnSubAgentSource : SubAgentSource
{
    [JsonPropertyName("thread_spawn")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public SubAgentSourceThreadSpawn ThreadSpawn { get; set; } = default!;

}
