// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadResumeResponse
{
    [JsonPropertyName("approvalPolicy")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public AskForApproval ApprovalPolicy { get; set; } = default!;

    /// <summary>
    ///     Reviewer currently used for approval requests on this thread.
    /// </summary>
    [JsonPropertyName("approvalsReviewer")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ApprovalsReviewer ApprovalsReviewer { get; set; } = default!;

    [JsonPropertyName("cwd")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Cwd { get; set; } = default!;

    /// <summary>
    ///     Environment-native paths to instruction source files currently loaded for this thread.
    /// </summary>
    [JsonPropertyName("instructionSources")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>> InstructionSources { get; set; }

    /// <summary>
    ///     Opaque cursor for hydrating paginated items backwards.
    ///     
    ///     Pass this as `cursor` to `thread/items/list` with `sortDirection: "desc"`. The first page includes the item identified by the cursor.
    /// </summary>
    [JsonPropertyName("itemsBackwardsCursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ItemsBackwardsCursor { get; set; }

    [JsonPropertyName("model")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Model { get; set; } = default!;

    [JsonPropertyName("modelProvider")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ModelProvider { get; set; } = default!;

    [JsonPropertyName("reasoningEffort")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ReasoningEffort { get; set; }

    /// <summary>
    ///     Legacy sandbox policy retained for compatibility. Experimental clients should prefer `activePermissionProfile` for profile provenance.
    /// </summary>
    [JsonPropertyName("sandbox")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public SandboxPolicy Sandbox { get; set; } = default!;

    [JsonPropertyName("serviceTier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ServiceTier { get; set; }

    [JsonPropertyName("thread")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public Thread Thread { get; set; } = default!;

    /// <summary>
    ///     Opaque cursor for hydrating paginated turns backwards.
    ///     
    ///     Pass this as `cursor` to `thread/turns/list` with `sortDirection: "desc"`. The first page includes the turn identified by the cursor.
    /// </summary>
    [JsonPropertyName("turnsBackwardsCursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> TurnsBackwardsCursor { get; set; }

}
