// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadTokenUsage
{
    [JsonPropertyName("last")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public TokenUsageBreakdown Last { get; set; } = default!;

    [JsonPropertyName("modelContextWindow")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> ModelContextWindow { get; set; }

    [JsonPropertyName("total")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public TokenUsageBreakdown Total { get; set; } = default!;

}
