// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadUsage
{
    [JsonPropertyName("estimatedUsageCreditsMicros")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public long EstimatedUsageCreditsMicros { get; set; } = default!;

    [JsonPropertyName("estimatedUsageUsdMicros")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> EstimatedUsageUsdMicros { get; set; }

    [JsonPropertyName("groups")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ThreadUsageBreakdownGroup> Groups { get; set; } = default!;

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
