// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadListCwdFilterArrayJsonConverter : JsonConverter<ThreadListCwdFilterArray>
{
    public override ThreadListCwdFilterArray Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<ThreadListCwdFilter>(ref reader, options) as ThreadListCwdFilterArray ?? throw new JsonException("Expected ThreadListCwdFilterArray.");
    public override void Write(Utf8JsonWriter writer, ThreadListCwdFilterArray concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
