// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadMetadataUpdateRequest : ClientRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "thread/metadata/update";
        private set
        {
            if (value != "thread/metadata/update")
            {
                throw new JsonException("Expected ThreadMetadataUpdateRequest.method to be thread/metadata/update.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadMetadataUpdateParams Params { get; set; } = default!;

}
