// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ThreadUnsubscribeStatusJsonConverter))]
public enum ThreadUnsubscribeStatus
{
    NotLoaded,
    NotSubscribed,
    Unsubscribed,
}
