// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadSectionDeleteRequest : ClientRequest
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public RequestId Id { get; set; } = default!;

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "threadSection/delete";
        private set
        {
            if (value != "threadSection/delete")
            {
                throw new JsonException("Expected ThreadSectionDeleteRequest.method to be threadSection/delete.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadSectionDeleteParams Params { get; set; } = default!;

}
