// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ThreadItemJsonConverter))]
public abstract class ThreadItem
{
    private protected ThreadItem() { }
}
