// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     DEPRECATED: `thread/rollback` will be removed soon.
/// </summary>
public class ThreadRollbackParams
{
    /// <summary>
    ///     The number of turns to drop from the end of the thread. Must be &gt;= 1.
    ///     
    ///     This only modifies the thread's history and does not revert local file changes that have been made by the agent. Clients are responsible for reverting these changes.
    /// </summary>
    [JsonPropertyName("numTurns")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public uint NumTurns { get; set; } = default!;

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
