// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Replace a paginated thread's durable history with the prefix before one turn.
///     
///     This only changes persisted conversation history. It does not revert local file changes.
/// </summary>
public class ThreadRevertParams
{
    /// <summary>
    ///     Turn excluded from the replacement history, together with every later turn.
    /// </summary>
    [JsonPropertyName("beforeTurnId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string BeforeTurnId { get; set; } = default!;

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
