// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadGoalStatusJsonConverter : JsonConverter<ThreadGoalStatus>
{
    private static ThreadGoalStatus Parse(string? value) => value switch
    {
        "active" => ThreadGoalStatus.Active,
        "blocked" => ThreadGoalStatus.Blocked,
        "budgetLimited" => ThreadGoalStatus.BudgetLimited,
        "complete" => ThreadGoalStatus.Complete,
        "paused" => ThreadGoalStatus.Paused,
        "usageLimited" => ThreadGoalStatus.UsageLimited,
        _ => throw new JsonException("Unknown ThreadGoalStatus value: " + value)
    };
    private static string Format(ThreadGoalStatus value) => value switch
    {
        ThreadGoalStatus.Active => "active",
        ThreadGoalStatus.Blocked => "blocked",
        ThreadGoalStatus.BudgetLimited => "budgetLimited",
        ThreadGoalStatus.Complete => "complete",
        ThreadGoalStatus.Paused => "paused",
        ThreadGoalStatus.UsageLimited => "usageLimited",
        _ => throw new JsonException("Unknown ThreadGoalStatus value: " + value)
    };
    public override ThreadGoalStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for ThreadGoalStatus.");
    public override void Write(Utf8JsonWriter writer, ThreadGoalStatus value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override ThreadGoalStatus ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, ThreadGoalStatus value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
