// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadProjectUpdatedNotification
{
    [JsonPropertyName("projectId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? ProjectId { get; set; } = default!;

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
