// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ThreadStartSourceJsonConverter))]
public enum ThreadStartSource
{
    Clear,
    Startup,
}
