// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadLoadedListParams
{
    /// <summary>
    ///     Opaque pagination cursor returned by a previous call.
    /// </summary>
    [JsonPropertyName("cursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Cursor { get; set; }

    /// <summary>
    ///     Optional page size; defaults to no limit.
    /// </summary>
    [JsonPropertyName("limit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<uint?> Limit { get; set; }

}
