// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ThreadListCwdFilterStringJsonConverter))]
public class ThreadListCwdFilterString : ThreadListCwdFilter
{
    public string Value { get; set; } = default!;
}
