// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL - role-bearing text item included when a realtime V3 session starts.
/// </summary>
public class ThreadRealtimeInitialItem
{
    [JsonPropertyName("role")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ConversationTextRole Role { get; set; } = default!;

    [JsonPropertyName("text")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Text { get; set; } = default!;

}
