// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL - thread realtime audio chunk.
/// </summary>
public class ThreadRealtimeAudioChunk
{
    [JsonPropertyName("data")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Data { get; set; } = default!;

    [JsonPropertyName("itemId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ItemId { get; set; }

    [JsonPropertyName("numChannels")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ushort NumChannels { get; set; } = default!;

    [JsonPropertyName("sampleRate")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public uint SampleRate { get; set; } = default!;

    [JsonPropertyName("samplesPerChannel")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<uint?> SamplesPerChannel { get; set; }

}
