// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadTokenUsageUpdatedNotification
{
    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

    [JsonPropertyName("tokenUsage")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadTokenUsage TokenUsage { get; set; } = default!;

    [JsonPropertyName("turnId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string TurnId { get; set; } = default!;

}
