// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadTimelineEntryJsonConverter : JsonConverter<ThreadTimelineEntry>
{
    public override ThreadTimelineEntry Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ThreadTimelineEntry type.");
        return discriminator.GetString() switch
        {
            "item" => root.Deserialize<ItemThreadTimelineEntry>(options) ?? throw new JsonException("Expected ItemThreadTimelineEntry."),
            "realtime" => root.Deserialize<RealtimeThreadTimelineEntry>(options) ?? throw new JsonException("Expected RealtimeThreadTimelineEntry."),
            "turnCompleted" => root.Deserialize<TurnCompletedThreadTimelineEntry>(options) ?? throw new JsonException("Expected TurnCompletedThreadTimelineEntry."),
            "turnStarted" => root.Deserialize<TurnStartedThreadTimelineEntry>(options) ?? throw new JsonException("Expected TurnStartedThreadTimelineEntry."),
            _ => throw new JsonException("Unknown ThreadTimelineEntry type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ThreadTimelineEntry value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case ItemThreadTimelineEntry concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case RealtimeThreadTimelineEntry concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case TurnCompletedThreadTimelineEntry concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case TurnStartedThreadTimelineEntry concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ThreadTimelineEntry.");
        }
    }
}
