// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadTurnsListResponse
{
    /// <summary>
    ///     Opaque cursor to pass as `cursor` when reversing `sortDirection`. This is only populated when the page contains at least one turn. Use it with the opposite `sortDirection` to include the anchor turn again and catch updates to that turn.
    /// </summary>
    [JsonPropertyName("backwardsCursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> BackwardsCursor { get; set; }

    [JsonPropertyName("data")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<Turn> Data { get; set; } = default!;

    /// <summary>
    ///     Opaque cursor to pass to the next call to continue after the last turn. if None, there are no more turns to return.
    /// </summary>
    [JsonPropertyName("nextCursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> NextCursor { get; set; }

}
