// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     Parameters for moving a thread within a server-owned section ordering.
/// </summary>
public class ThreadSectionMoveParams
{
    /// <summary>
    ///     Existing thread to insert before; omission or null appends to the section.
    /// </summary>
    [JsonPropertyName("beforeThreadId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> BeforeThreadId { get; set; }

    /// <summary>
    ///     Destination section, or `null` to remove the thread from its section.
    /// </summary>
    [JsonPropertyName("sectionId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? SectionId { get; set; } = default!;

    /// <summary>
    ///     Thread to move into, within, or out of a section.
    /// </summary>
    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
