// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ThreadRealtimeSessionOutcomeJsonConverter))]
public enum ThreadRealtimeSessionOutcome
{
    Ended,
    Failed,
}
