// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadTurnsListParams
{
    /// <summary>
    ///     Opaque cursor to pass to the next call to continue after the last turn.
    /// </summary>
    [JsonPropertyName("cursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Cursor { get; set; }

    /// <summary>
    ///     How much item detail to include for each returned turn; defaults to summary.
    /// </summary>
    [JsonPropertyName("itemsView")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<TurnItemsView?> ItemsView { get; set; }

    /// <summary>
    ///     Optional turn page size.
    /// </summary>
    [JsonPropertyName("limit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<uint?> Limit { get; set; }

    /// <summary>
    ///     Optional turn pagination direction; defaults to descending.
    /// </summary>
    [JsonPropertyName("sortDirection")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SortDirection?> SortDirection { get; set; }

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
