// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     The independently persisted section created by the server.
/// </summary>
public class ThreadSectionCreateResponse
{
    [JsonPropertyName("section")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadSection Section { get; set; } = default!;

}
