// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadStartParams
{
    [JsonPropertyName("approvalPolicy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<AskForApproval?> ApprovalPolicy { get; set; }

    /// <summary>
    ///     Override where approval requests are routed for review on this thread and subsequent turns.
    /// </summary>
    [JsonPropertyName("approvalsReviewer")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ApprovalsReviewer?> ApprovalsReviewer { get; set; }

    [JsonPropertyName("baseInstructions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> BaseInstructions { get; set; }

    [JsonPropertyName("config")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Dictionary<string, JsonElement>?> Config { get; set; }

    [JsonPropertyName("cwd")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Cwd { get; set; }

    [JsonPropertyName("developerInstructions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> DeveloperInstructions { get; set; }

    [JsonPropertyName("ephemeral")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool?> Ephemeral { get; set; }

    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> Model { get; set; }

    [JsonPropertyName("modelProvider")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ModelProvider { get; set; }

    [JsonPropertyName("personality")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<Personality?> Personality { get; set; }

    [JsonPropertyName("sandbox")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<SandboxMode?> Sandbox { get; set; }

    [JsonPropertyName("serviceName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ServiceName { get; set; }

    [JsonPropertyName("serviceTier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ServiceTier { get; set; }

    [JsonPropertyName("sessionStartSource")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ThreadStartSource?> SessionStartSource { get; set; }

    /// <summary>
    ///     Optional client-supplied analytics source classification for this thread.
    /// </summary>
    [JsonPropertyName("threadSource")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> ThreadSource { get; set; }

}
