// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadLoadedListResponse
{
    /// <summary>
    ///     Thread ids for sessions currently loaded in memory.
    /// </summary>
    [JsonPropertyName("data")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> Data { get; set; } = default!;

    /// <summary>
    ///     Opaque cursor to pass to the next call to continue after the last item. if None, there are no more items to return.
    /// </summary>
    [JsonPropertyName("nextCursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> NextCursor { get; set; }

}
