// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadRealtimeItemTranscriptDeltaNotification2 : ServerNotification
{
    /// <summary>
    ///     Unix timestamp (in milliseconds) when app-server emitted this notification.
    /// </summary>
    [JsonPropertyName("emittedAtMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long> EmittedAtMs { get; set; }

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "thread/realtime/item/transcript/delta";
        private set
        {
            if (value != "thread/realtime/item/transcript/delta")
            {
                throw new JsonException("Expected ThreadRealtimeItemTranscriptDeltaNotification2.method to be thread/realtime/item/transcript/delta.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadRealtimeItemTranscriptDeltaNotification Params { get; set; } = default!;

}
