// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(ThreadStatusJsonConverter))]
public abstract class ThreadStatus
{
    private protected ThreadStatus() { }
}
