// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadGoalSetResponse
{
    [JsonPropertyName("goal")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadGoal Goal { get; set; } = default!;

}
