// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadHistoryModeJsonConverter : JsonConverter<ThreadHistoryMode>
{
    private static ThreadHistoryMode Parse(string? value) => value switch
    {
        "legacy" => ThreadHistoryMode.Legacy,
        "paginated" => ThreadHistoryMode.Paginated,
        _ => throw new JsonException("Unknown ThreadHistoryMode value: " + value)
    };
    private static string Format(ThreadHistoryMode value) => value switch
    {
        ThreadHistoryMode.Legacy => "legacy",
        ThreadHistoryMode.Paginated => "paginated",
        _ => throw new JsonException("Unknown ThreadHistoryMode value: " + value)
    };
    public override ThreadHistoryMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for ThreadHistoryMode.");
    public override void Write(Utf8JsonWriter writer, ThreadHistoryMode value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override ThreadHistoryMode ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, ThreadHistoryMode value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
