// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadMemoryModeJsonConverter : JsonConverter<ThreadMemoryMode>
{
    private static ThreadMemoryMode Parse(string? value) => value switch
    {
        "disabled" => ThreadMemoryMode.Disabled,
        "enabled" => ThreadMemoryMode.Enabled,
        _ => throw new JsonException("Unknown ThreadMemoryMode value: " + value)
    };
    private static string Format(ThreadMemoryMode value) => value switch
    {
        ThreadMemoryMode.Disabled => "disabled",
        ThreadMemoryMode.Enabled => "enabled",
        _ => throw new JsonException("Unknown ThreadMemoryMode value: " + value)
    };
    public override ThreadMemoryMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for ThreadMemoryMode.");
    public override void Write(Utf8JsonWriter writer, ThreadMemoryMode value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override ThreadMemoryMode ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, ThreadMemoryMode value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
