// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadMetadataUpdateParams
{
    /// <summary>
    ///     Patch the stored Git metadata for this thread. Omit a field to leave it unchanged, set it to `null` to clear it, or provide a string to replace the stored value.
    /// </summary>
    [JsonPropertyName("gitInfo")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<ThreadMetadataGitInfoUpdateParams?> GitInfo { get; set; }

    [JsonPropertyName("threadId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ThreadId { get; set; } = default!;

}
