// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadListCwdFilterStringJsonConverter : JsonConverter<ThreadListCwdFilterString>
{
    public override ThreadListCwdFilterString Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize<ThreadListCwdFilter>(ref reader, options) as ThreadListCwdFilterString ?? throw new JsonException("Expected ThreadListCwdFilterString.");
    public override void Write(Utf8JsonWriter writer, ThreadListCwdFilterString concrete, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, concrete.Value, options);
    }
}
