// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadItemsListResponse
{
    /// <summary>
    ///     Opaque cursor to pass as `cursor` when reversing `sortDirection`. This is only populated when the page contains at least one item.
    /// </summary>
    [JsonPropertyName("backwardsCursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> BackwardsCursor { get; set; }

    [JsonPropertyName("data")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ThreadItemEntry> Data { get; set; } = default!;

    /// <summary>
    ///     Opaque cursor to pass to the next call to continue after the last item. if None, there are no more items to return.
    /// </summary>
    [JsonPropertyName("nextCursor")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> NextCursor { get; set; }

}
