// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ThreadRealtimeStartTransportJsonConverter : JsonConverter<ThreadRealtimeStartTransport>
{
    public override ThreadRealtimeStartTransport Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object || !root.TryGetProperty("type", out var discriminator) || discriminator.ValueKind != JsonValueKind.String)
            throw new JsonException("Missing or invalid ThreadRealtimeStartTransport type.");
        return discriminator.GetString() switch
        {
            "existingCall" => root.Deserialize<ExistingCallThreadRealtimeStartTransport>(options) ?? throw new JsonException("Expected ExistingCallThreadRealtimeStartTransport."),
            "webrtc" => root.Deserialize<WebrtcThreadRealtimeStartTransport>(options) ?? throw new JsonException("Expected WebrtcThreadRealtimeStartTransport."),
            "websocket" => root.Deserialize<WebsocketThreadRealtimeStartTransport>(options) ?? throw new JsonException("Expected WebsocketThreadRealtimeStartTransport."),
            _ => throw new JsonException("Unknown ThreadRealtimeStartTransport type \u0027" + discriminator.GetString() + "\u0027.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ThreadRealtimeStartTransport value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case ExistingCallThreadRealtimeStartTransport concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WebrtcThreadRealtimeStartTransport concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            case WebsocketThreadRealtimeStartTransport concrete:
                JsonSerializer.Serialize(writer, concrete, options);
                break;
            default: throw new JsonException("Unknown runtime type for ThreadRealtimeStartTransport.");
        }
    }
}
