// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL. Captures a user's answer to a request_user_input question.
/// </summary>
public class ToolRequestUserInputAnswer
{
    [JsonPropertyName("answers")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<string> Answers { get; set; } = default!;

}
