// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     EXPERIMENTAL. Defines a single selectable option for request_user_input.
/// </summary>
public class ToolRequestUserInputOption
{
    [JsonPropertyName("description")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Description { get; set; } = default!;

    [JsonPropertyName("label")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Label { get; set; } = default!;

}
