// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class ToolsV2
{
    [JsonPropertyName("web_search")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<WebSearchToolConfig?> WebSearch { get; set; }

}
