// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class TranscriptSegmentThreadRealtimeItem : ThreadRealtimeItem
{
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    [JsonPropertyName("realtimeSessionId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string RealtimeSessionId { get; set; } = default!;

    [JsonPropertyName("role")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ThreadRealtimeTranscriptRole Role { get; set; } = default!;

    [JsonPropertyName("text")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Text { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "transcriptSegment";
        private set
        {
            if (value != "transcriptSegment")
            {
                throw new JsonException("Expected TranscriptSegmentThreadRealtimeItem.type to be transcriptSegment.");
            }
        }
    }

}
