// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class Turn
{
    /// <summary>
    ///     Unix timestamp (in seconds) when the turn completed.
    /// </summary>
    [JsonPropertyName("completedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> CompletedAt { get; set; }

    /// <summary>
    ///     Duration between turn start and completion in milliseconds, if known.
    /// </summary>
    [JsonPropertyName("durationMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> DurationMs { get; set; }

    /// <summary>
    ///     Only populated when the Turn's status is failed.
    /// </summary>
    [JsonPropertyName("error")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<TurnError?> Error { get; set; }

    /// <summary>
    ///     Identifier for this turn. Codex-generated turn IDs are UUIDv7.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Id { get; set; } = default!;

    /// <summary>
    ///     Thread items currently included in this turn payload.
    /// </summary>
    [JsonPropertyName("items")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public List<ThreadItem> Items { get; set; } = default!;

    /// <summary>
    ///     Describes how much of `items` has been loaded for this turn.
    /// </summary>
    [JsonPropertyName("itemsView")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<TurnItemsView> ItemsView { get; set; }

    /// <summary>
    ///     Unix timestamp (in seconds) when the turn started.
    /// </summary>
    [JsonPropertyName("startedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> StartedAt { get; set; }

    [JsonPropertyName("status")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public TurnStatus Status { get; set; } = default!;

}
