// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class TurnError
{
    [JsonPropertyName("additionalDetails")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> AdditionalDetails { get; set; }

    [JsonPropertyName("codexErrorInfo")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<CodexErrorInfo?> CodexErrorInfo { get; set; }

    [JsonPropertyName("message")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Message { get; set; } = default!;

    /// <summary>
    ///     Optional public explanation and continuation instruction for a misalignment block.
    /// </summary>
    [JsonPropertyName("misalignment")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<MisalignmentErrorDetails?> Misalignment { get; set; }

}
