// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class TurnStartedNotification2 : ServerNotification
{
    /// <summary>
    ///     Unix timestamp (in milliseconds) when app-server emitted this notification.
    /// </summary>
    [JsonPropertyName("emittedAtMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long> EmittedAtMs { get; set; }

    [JsonPropertyName("method")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Method
    {
        get => "turn/started";
        private set
        {
            if (value != "turn/started")
            {
                throw new JsonException("Expected TurnStartedNotification2.method to be turn/started.");
            }
        }
    }

    [JsonPropertyName("params")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public TurnStartedNotification Params { get; set; } = default!;

}
