// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class TurnStatusJsonConverter : JsonConverter<TurnStatus>
{
    private static TurnStatus Parse(string? value) => value switch
    {
        "completed" => TurnStatus.Completed,
        "failed" => TurnStatus.Failed,
        "inProgress" => TurnStatus.InProgress,
        "interrupted" => TurnStatus.Interrupted,
        _ => throw new JsonException("Unknown TurnStatus value: " + value)
    };
    private static string Format(TurnStatus value) => value switch
    {
        TurnStatus.Completed => "completed",
        TurnStatus.Failed => "failed",
        TurnStatus.InProgress => "inProgress",
        TurnStatus.Interrupted => "interrupted",
        _ => throw new JsonException("Unknown TurnStatus value: " + value)
    };
    public override TurnStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for TurnStatus.");
    public override void Write(Utf8JsonWriter writer, TurnStatus value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override TurnStatus ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, TurnStatus value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
