// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class UnknownCommandAction : CommandAction
{
    [JsonPropertyName("command")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Command { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "unknown";
        private set
        {
            if (value != "unknown")
            {
                throw new JsonException("Expected UnknownCommandAction.type to be unknown.");
            }
        }
    }

}
