// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class UnknownParsedCommand : ParsedCommand
{
    [JsonPropertyName("cmd")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Cmd { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "unknown";
        private set
        {
            if (value != "unknown")
            {
                throw new JsonException("Expected UnknownParsedCommand.type to be unknown.");
            }
        }
    }

}
