// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class UpdateFileChange : FileChange
{
    [JsonPropertyName("move_path")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<string?> MovePath { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "update";
        private set
        {
            if (value != "update")
            {
                throw new JsonException("Expected UpdateFileChange.type to be update.");
            }
        }
    }

    [JsonPropertyName("unified_diff")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string UnifiedDiff { get; set; } = default!;

}
