// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class UsageLimitExceededImageGenerationFailure : ImageGenerationFailure
{
    [JsonPropertyName("limitId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string LimitId { get; set; } = default!;

    [JsonPropertyName("resetsAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<long?> ResetsAt { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "usageLimitExceeded";
        private set
        {
            if (value != "usageLimitExceeded")
            {
                throw new JsonException("Expected UsageLimitExceededImageGenerationFailure.type to be usageLimitExceeded.");
            }
        }
    }

}
