// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class VerbosityJsonConverter : JsonConverter<Verbosity>
{
    private static Verbosity Parse(string? value) => value switch
    {
        "high" => Verbosity.High,
        "low" => Verbosity.Low,
        "medium" => Verbosity.Medium,
        _ => throw new JsonException("Unknown Verbosity value: " + value)
    };
    private static string Format(Verbosity value) => value switch
    {
        Verbosity.High => "high",
        Verbosity.Low => "low",
        Verbosity.Medium => "medium",
        _ => throw new JsonException("Unknown Verbosity value: " + value)
    };
    public override Verbosity Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for Verbosity.");
    public override void Write(Utf8JsonWriter writer, Verbosity value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override Verbosity ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, Verbosity value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
