// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class WebrtcThreadRealtimeStartTransport : ThreadRealtimeStartTransport
{
    /// <summary>
    ///     SDP offer generated by a WebRTC RTCPeerConnection after configuring audio and the realtime events data channel.
    /// </summary>
    [JsonPropertyName("sdp")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Sdp { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "webrtc";
        private set
        {
            if (value != "webrtc")
            {
                throw new JsonException("Expected WebrtcThreadRealtimeStartTransport.type to be webrtc.");
            }
        }
    }

}
