// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(WebSearchModeJsonConverter))]
public enum WebSearchMode
{
    Cached,
    Disabled,
    Indexed,
    Live,
}
