// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class WeekdaysScheduledTaskSchedule : ScheduledTaskSchedule
{
    [JsonPropertyName("time")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Time { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "weekdays";
        private set
        {
            if (value != "weekdays")
            {
                throw new JsonException("Expected WeekdaysScheduledTaskSchedule.type to be weekdays.");
            }
        }
    }

}
