// <auto-generated />
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class WindowsSandboxSetupModeJsonConverter : JsonConverter<WindowsSandboxSetupMode>
{
    private static WindowsSandboxSetupMode Parse(string? value) => value switch
    {
        "elevated" => WindowsSandboxSetupMode.Elevated,
        "unelevated" => WindowsSandboxSetupMode.Unelevated,
        _ => throw new JsonException("Unknown WindowsSandboxSetupMode value: " + value)
    };
    private static string Format(WindowsSandboxSetupMode value) => value switch
    {
        WindowsSandboxSetupMode.Elevated => "elevated",
        WindowsSandboxSetupMode.Unelevated => "unelevated",
        _ => throw new JsonException("Unknown WindowsSandboxSetupMode value: " + value)
    };
    public override WindowsSandboxSetupMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        reader.TokenType == JsonTokenType.String ? Parse(reader.GetString()) : throw new JsonException("Expected a string for WindowsSandboxSetupMode.");
    public override void Write(Utf8JsonWriter writer, WindowsSandboxSetupMode value, JsonSerializerOptions options) => writer.WriteStringValue(Format(value));
    public override WindowsSandboxSetupMode ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => Parse(reader.GetString());
    public override void WriteAsPropertyName(Utf8JsonWriter writer, WindowsSandboxSetupMode value, JsonSerializerOptions options) => writer.WritePropertyName(Format(value));
}
