// <auto-generated />
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

public class WorkspaceWriteSandboxPolicy : SandboxPolicy
{
    [JsonPropertyName("excludeSlashTmp")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> ExcludeSlashTmp { get; set; }

    [JsonPropertyName("excludeTmpdirEnvVar")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> ExcludeTmpdirEnvVar { get; set; }

    [JsonPropertyName("networkAccess")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<bool> NetworkAccess { get; set; }

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "workspaceWrite";
        private set
        {
            if (value != "workspaceWrite")
            {
                throw new JsonException("Expected WorkspaceWriteSandboxPolicy.type to be workspaceWrite.");
            }
        }
    }

    [JsonPropertyName("writableRoots")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Optional<List<string>> WritableRoots { get; set; }

}
