// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

/// <summary>
///     A child approval for input to an existing command execution item.
/// </summary>
public class WriteStdinGuardianApprovalReviewAction : GuardianApprovalReviewAction
{
    [JsonPropertyName("approvalId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ApprovalId { get; set; } = default!;

    [JsonPropertyName("cwd")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Cwd { get; set; } = default!;

    [JsonPropertyName("processId")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string ProcessId { get; set; } = default!;

    [JsonPropertyName("stdin")]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Stdin { get; set; } = default!;

    [JsonPropertyName("type")]
    [JsonInclude]
    [JsonRequired]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string Type
    {
        get => "writeStdin";
        private set
        {
            if (value != "writeStdin")
            {
                throw new JsonException("Expected WriteStdinGuardianApprovalReviewAction.type to be writeStdin.");
            }
        }
    }

}
