using System.Text;
using ZYC.Codex.Protocol.Generator.Model;

namespace ZYC.Codex.Protocol.Generator.Generation;

public class CSharpGenerator
{
    public IReadOnlyDictionary<string, string> Generate(IReadOnlyList<TypeModel> types)
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);

        void Add(string name, Action<CodeWriter> write, IEnumerable<TypeReference>? references = null,
            bool converter = false, bool serialization = true, IEnumerable<string>? additionalImports = null)
        {
            var imports = new SortedSet<string>(StringComparer.Ordinal);
            imports.UnionWith(additionalImports ?? []);
            if (serialization)
            {
                imports.Add("System.Text.Json.Serialization");
            }

            if (converter)
            {
                imports.Add("System");
                imports.Add("System.Text.Json");
            }

            foreach (var type in references ?? [])
            {
                CSharpTypeWriter.Imports(type, imports);
            }

            var writer = new CodeWriter();
            writer.Line("// <auto-generated />");
            writer.Line("#nullable enable");
            writer.Line();
            foreach (var ns in imports)
            {
                writer.Line($"using {ns};");
            }

            if (imports.Count > 0)
            {
                writer.Line();
            }

            writer.Line("namespace ZYC.Codex.Protocol;");
            writer.Line();
            write(writer);
            files.Add(name + ".g.cs", writer.ToString());
        }

        foreach (var model in types.OrderBy(t => t.Name, StringComparer.Ordinal))
        {
            switch (model)
            {
                case NullTypeModel empty:
                    Add(empty.Name, w =>
                    {
                        w.Line($"[JsonConverter(typeof({empty.Name}JsonConverter))]");
                        w.Line($"public struct {empty.Name} {{ }}");
                    });
                    Add(empty.Name + "JsonConverter", w => CSharpConverterWriter.Null(w, empty), converter: true);
                    break;
                case ObjectTypeModel obj:
                    var refs = obj.Properties.Where(p => p.Constant == null).Select(p => p.Type).ToList();
                    if (obj.ExtensionDataName != null)
                    {
                        refs.Add(new TypeReference(TypeKind.Dictionary, Element: new TypeReference(TypeKind.Any)));
                    }

                    Add(obj.Name, w => CSharpTypeWriter.Object(w, obj), refs,
                        serialization: obj.Properties.Count > 0 || obj.ExtensionDataName != null || obj.Closed,
                        additionalImports: obj.Properties.Any(p => p.Constant != null) ? ["System.Text.Json"] : null);
                    break;
                case EnumTypeModel en:
                    Add(en.Name, w => CSharpTypeWriter.Enum(w, en));
                    Add(en.Name + "JsonConverter", w => CSharpConverterWriter.Enum(w, en), converter: true);
                    break;
                case UnionTypeModel union:
                    Add(union.Name, w => CSharpUnionWriter.Base(w, union),
                        additionalImports: union.HasValueSemantics ? ["System", "System.Collections.Generic"] : null);
                    Add(union.Name + "JsonConverter", w => CSharpConverterWriter.Union(w, union),
                        union.Members.Where(m => m.Payload != null).Select(m => m.Payload!), true);
                    foreach (var member in union.Members.Where(m => m.Payload != null || m.Literal != null))
                    {
                        TypeReference[] payload = member.Payload == null ? [] : [member.Payload];
                        Add(member.TypeName, w => CSharpUnionWriter.Member(w, union, member), payload,
                            additionalImports: union.HasValueSemantics && member.Payload?.Name == "string" ? ["System"] : null);
                        Add(member.TypeName + "JsonConverter", w => CSharpConverterWriter.Member(w, union, member),
                            payload, true);
                    }

                    break;
                default: throw new NotSupportedException($"Unknown IR model {model.Name}.");
            }
        }

        return files;
    }

    public void Write(IReadOnlyList<TypeModel> types, string outputDirectory)
    {
        // Finish analysis and rendering before touching a previous successful generation.
        var files = Generate(types);
        var output = Path.GetFullPath(outputDirectory);
        Directory.CreateDirectory(output);
        foreach (var oldFile in Directory.EnumerateFiles(output, "*.g.cs", SearchOption.TopDirectoryOnly))
        {
            File.Delete(oldFile);
        }

        foreach (var (name, content) in files)
        {
            File.WriteAllText(Path.Combine(output, name), content, new UTF8Encoding(false));
        }
    }
}
