// <auto-generated />
#nullable enable

using System.Text.Json.Serialization;

namespace ZYC.Codex.Protocol;

[JsonConverter(typeof(FixtureEnumJsonConverter))]
public enum FixtureEnum
{
    FooBar,
    SnakeCase,
    ThreadStart,
}
