name: push-nuget
on:
  workflow_dispatch:
  
jobs:
  push-nuget:
    runs-on: windows-latest
    # runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        dotnet run --project ZYC.Codex.Protocol.Generator/ZYC.Codex.Protocol.Generator.csproj -c release --property:DefineConstants="PUSH_NUGET"
